/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mdiFrota.java
 *
 * Created on 07/10/2009, 10:06:32
 */

package sistemadefrota;

import controle.CadFornecedores;
import controle.Carroceria;
import controle.Categoria;
import controle.Chaves;
import controle.ChavesDevolucao;
import controle.Cidade;
import controle.Combustivel;
import controle.ConsultaMotorista;
import controle.ConsultaVeiculo;
import controle.Cor;
import controle.Especie;
import controle.Estado;
import controle.Evento;
import controle.Evento_Item;
import controle.ImpressaoFornecedor;
import controle.ImpressaoHistoricoCarro;
import controle.ImpressaoMotorista;
import controle.ImpressaoMovimentacao;
import controle.ImpressaoMulta;
import controle.ImpressaoNotaFiscal;
import controle.ImpressaoPontuacao;
import controle.ImpressaoRendimento;
import controle.ImpressaoVeiculo;
import controle.Infracoes;
import controle.Manutencao;
import controle.Marca;
import controle.Modelo;
import controle.Motorista;
import controle.Movimentacao;
import controle.Multa;
import controle.NotaFiscal;
import controle.Pontos;
import controle.Produto;
import controle.Rastrear;
import controle.Restricao;
import controle.Sobre;
import controle.Veiculo;
import controle.Seguro;
import javax.swing.UIManager;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jeferson
 */
public class mdiFrota extends javax.swing.JFrame {
    
    //DecoratedDesktopPane jdpMdiFrota = new DecoratedDesktopPane("C:/java.jpg");

    /** Creates new form mdiFrota */
    public mdiFrota() {
        
        try {            
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());  
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e){            
            e.printStackTrace();            
        }
        
        initComponents();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jdpMdiFrota = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnCadastro = new javax.swing.JMenu();
        jmnFederacoes = new javax.swing.JMenu();
        jmiEstado = new javax.swing.JMenuItem();
        jmiCidade = new javax.swing.JMenuItem();
        jmnTipoVeiculo = new javax.swing.JMenu();
        jmiMarca = new javax.swing.JMenuItem();
        jmiModelo = new javax.swing.JMenuItem();
        jmnEventos = new javax.swing.JMenu();
        jmiEventos = new javax.swing.JMenuItem();
        jmiEventosItem = new javax.swing.JMenuItem();
        jmnTipos = new javax.swing.JMenu();
        jmiCarroceria = new javax.swing.JMenuItem();
        jmiCategoria = new javax.swing.JMenuItem();
        jmiCombustivel = new javax.swing.JMenuItem();
        jmiCor = new javax.swing.JMenuItem();
        jmiEspecie = new javax.swing.JMenuItem();
        jmiRestricao = new javax.swing.JMenuItem();
        jmnManutencao = new javax.swing.JMenu();
        jmiManutencao = new javax.swing.JMenuItem();
        jmiSeguro = new javax.swing.JMenuItem();
        jmiInfracoes = new javax.swing.JMenuItem();
        jmiMotorista = new javax.swing.JMenuItem();
        jmiVeiculo = new javax.swing.JMenuItem();
        jmiFornecedores = new javax.swing.JMenuItem();
        jmiProduto = new javax.swing.JMenuItem();
        jmnMovimentacao = new javax.swing.JMenu();
        jmiNF = new javax.swing.JMenuItem();
        jmiMovFrota = new javax.swing.JMenuItem();
        jmnCarro = new javax.swing.JMenu();
        jmiChaves = new javax.swing.JMenuItem();
        jmiDevolucaoChaves = new javax.swing.JMenuItem();
        jmiRastrear = new javax.swing.JMenuItem();
        jmnMulta = new javax.swing.JMenu();
        jmiLancamentoMultas = new javax.swing.JMenuItem();
        jmiRankingMultas = new javax.swing.JMenuItem();
        jmnConsulta = new javax.swing.JMenu();
        jmnVeiculo = new javax.swing.JMenuItem();
        jmiConsultaMotorista = new javax.swing.JMenuItem();
        jmnImpressão = new javax.swing.JMenu();
        jmnImpressaoCadastro = new javax.swing.JMenu();
        jmiImpressaoMotorista = new javax.swing.JMenuItem();
        jmiImpressaoVeiculo = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jmiImpInfraTransito = new javax.swing.JMenuItem();
        jmnImpressaoMovimetacao = new javax.swing.JMenu();
        jmiImpressaoNF = new javax.swing.JMenuItem();
        jmiImpressaoMovimentacao = new javax.swing.JMenuItem();
        jmiImpressaoCarro = new javax.swing.JMenu();
        jmiHistoricoCarro = new javax.swing.JMenuItem();
        jmiRendimento = new javax.swing.JMenuItem();
        jmuImpressaoMulta = new javax.swing.JMenu();
        jmiImpressaoPontuacao = new javax.swing.JMenuItem();
        jmnSobre = new javax.swing.JMenu();
        jmiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Frota 0.1 - Release Candidate 3");

        jdpMdiFrota.setBackground(new java.awt.Color(204, 204, 204));
        jdpMdiFrota.setForeground(new java.awt.Color(224, 224, 224));

        jmnCadastro.setText("Cadastro");
        jmnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnCadastroActionPerformed(evt);
            }
        });

        jmnFederacoes.setText("Federações");

        jmiEstado.setText("Estado");
        jmiEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEstadoActionPerformed(evt);
            }
        });
        jmnFederacoes.add(jmiEstado);

        jmiCidade.setText("Cidade");
        jmiCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCidadeActionPerformed(evt);
            }
        });
        jmnFederacoes.add(jmiCidade);

        jmnCadastro.add(jmnFederacoes);

        jmnTipoVeiculo.setText("Tipo de Veículos");

        jmiMarca.setText("Marca");
        jmiMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMarcaActionPerformed(evt);
            }
        });
        jmnTipoVeiculo.add(jmiMarca);

        jmiModelo.setText("Modelo");
        jmiModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModeloActionPerformed(evt);
            }
        });
        jmnTipoVeiculo.add(jmiModelo);

        jmnCadastro.add(jmnTipoVeiculo);

        jmnEventos.setText("Eventos");

        jmiEventos.setText("Eventos");
        jmiEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEventosActionPerformed(evt);
            }
        });
        jmnEventos.add(jmiEventos);

        jmiEventosItem.setText("Item dos Eventos");
        jmiEventosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEventosItemActionPerformed(evt);
            }
        });
        jmnEventos.add(jmiEventosItem);

        jmnCadastro.add(jmnEventos);

        jmnTipos.setText("Tipos");

        jmiCarroceria.setText("Carroceria");
        jmiCarroceria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCarroceriaActionPerformed(evt);
            }
        });
        jmnTipos.add(jmiCarroceria);

        jmiCategoria.setText("Categoria");
        jmiCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCategoriaActionPerformed(evt);
            }
        });
        jmnTipos.add(jmiCategoria);

        jmiCombustivel.setText("Combustível");
        jmiCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCombustivelActionPerformed(evt);
            }
        });
        jmnTipos.add(jmiCombustivel);

        jmiCor.setText("Cor");
        jmiCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCorActionPerformed(evt);
            }
        });
        jmnTipos.add(jmiCor);

        jmiEspecie.setText("Espécie");
        jmiEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEspecieActionPerformed(evt);
            }
        });
        jmnTipos.add(jmiEspecie);

        jmiRestricao.setText("Restrição");
        jmiRestricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRestricaoActionPerformed(evt);
            }
        });
        jmnTipos.add(jmiRestricao);

        jmnCadastro.add(jmnTipos);

        jmnManutencao.setText("Manutenção");

        jmiManutencao.setText("Manutenção");
        jmiManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManutencaoActionPerformed(evt);
            }
        });
        jmnManutencao.add(jmiManutencao);

        jmnCadastro.add(jmnManutencao);

        jmiSeguro.setText("Seguro");
        jmiSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSeguroActionPerformed(evt);
            }
        });
        jmnCadastro.add(jmiSeguro);

        jmiInfracoes.setText("Infrações de Trânsito");
        jmiInfracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInfracoesActionPerformed(evt);
            }
        });
        jmnCadastro.add(jmiInfracoes);

        jmiMotorista.setText("Motorista");
        jmiMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMotoristaActionPerformed(evt);
            }
        });
        jmnCadastro.add(jmiMotorista);

        jmiVeiculo.setText("Veículo");
        jmiVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVeiculoActionPerformed(evt);
            }
        });
        jmnCadastro.add(jmiVeiculo);

        jmiFornecedores.setText("Fornecedores");
        jmiFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedoresActionPerformed(evt);
            }
        });
        jmnCadastro.add(jmiFornecedores);

        jmiProduto.setText("Produto");
        jmiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutoActionPerformed(evt);
            }
        });
        jmnCadastro.add(jmiProduto);

        jMenuBar1.add(jmnCadastro);

        jmnMovimentacao.setText("Movimentação");

        jmiNF.setText("Nota Fiscal");
        jmiNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNFActionPerformed(evt);
            }
        });
        jmnMovimentacao.add(jmiNF);

        jmiMovFrota.setText("Movimentação Frota");
        jmiMovFrota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMovFrotaActionPerformed(evt);
            }
        });
        jmnMovimentacao.add(jmiMovFrota);

        jMenuBar1.add(jmnMovimentacao);

        jmnCarro.setText("Carro");

        jmiChaves.setText("Chaves");
        jmiChaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiChavesActionPerformed(evt);
            }
        });
        jmnCarro.add(jmiChaves);

        jmiDevolucaoChaves.setText("Devolução de Chaves");
        jmiDevolucaoChaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDevolucaoChavesActionPerformed(evt);
            }
        });
        jmnCarro.add(jmiDevolucaoChaves);

        jmiRastrear.setText("Rastrear");
        jmiRastrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRastrearActionPerformed(evt);
            }
        });
        jmnCarro.add(jmiRastrear);

        jMenuBar1.add(jmnCarro);

        jmnMulta.setText("Multas");

        jmiLancamentoMultas.setText("Lançamento de Multas");
        jmiLancamentoMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLancamentoMultasActionPerformed(evt);
            }
        });
        jmnMulta.add(jmiLancamentoMultas);

        jmiRankingMultas.setText("Ranking de Pontos");
        jmiRankingMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRankingMultasActionPerformed(evt);
            }
        });
        jmnMulta.add(jmiRankingMultas);

        jMenuBar1.add(jmnMulta);

        jmnConsulta.setText("Consulta");

        jmnVeiculo.setText("Veículo");
        jmnVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnVeiculoActionPerformed(evt);
            }
        });
        jmnConsulta.add(jmnVeiculo);

        jmiConsultaMotorista.setText("Motorista");
        jmiConsultaMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaMotoristaActionPerformed(evt);
            }
        });
        jmnConsulta.add(jmiConsultaMotorista);

        jMenuBar1.add(jmnConsulta);

        jmnImpressão.setText("Impressão");

        jmnImpressaoCadastro.setText("Cadastro");

        jmiImpressaoMotorista.setText("Motorista");
        jmiImpressaoMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImpressaoMotoristaActionPerformed(evt);
            }
        });
        jmnImpressaoCadastro.add(jmiImpressaoMotorista);

        jmiImpressaoVeiculo.setText("Veículo");
        jmiImpressaoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImpressaoVeiculoActionPerformed(evt);
            }
        });
        jmnImpressaoCadastro.add(jmiImpressaoVeiculo);

        jmiFornecedor.setText("Fornecedor");
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jmnImpressaoCadastro.add(jmiFornecedor);

        jmiImpInfraTransito.setText("Infrações de Trânsito");
        jmiImpInfraTransito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImpInfraTransitoActionPerformed(evt);
            }
        });
        jmnImpressaoCadastro.add(jmiImpInfraTransito);

        jmnImpressão.add(jmnImpressaoCadastro);

        jmnImpressaoMovimetacao.setText("Movimentação");

        jmiImpressaoNF.setText("Nota Fiscal");
        jmiImpressaoNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImpressaoNFActionPerformed(evt);
            }
        });
        jmnImpressaoMovimetacao.add(jmiImpressaoNF);

        jmiImpressaoMovimentacao.setText("Movimentação da Frota");
        jmiImpressaoMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImpressaoMovimentacaoActionPerformed(evt);
            }
        });
        jmnImpressaoMovimetacao.add(jmiImpressaoMovimentacao);

        jmnImpressão.add(jmnImpressaoMovimetacao);

        jmiImpressaoCarro.setText("Carro");

        jmiHistoricoCarro.setText("Histórico");
        jmiHistoricoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHistoricoCarroActionPerformed(evt);
            }
        });
        jmiImpressaoCarro.add(jmiHistoricoCarro);

        jmiRendimento.setText("Rendimento");
        jmiRendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRendimentoActionPerformed(evt);
            }
        });
        jmiImpressaoCarro.add(jmiRendimento);

        jmnImpressão.add(jmiImpressaoCarro);

        jmuImpressaoMulta.setText("Multa");

        jmiImpressaoPontuacao.setText("Pontuação");
        jmiImpressaoPontuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImpressaoPontuacaoActionPerformed(evt);
            }
        });
        jmuImpressaoMulta.add(jmiImpressaoPontuacao);

        jmnImpressão.add(jmuImpressaoMulta);

        jMenuBar1.add(jmnImpressão);

        jmnSobre.setText("Sobre");

        jmiSobre.setText("Sobre o Sistema");
        jmiSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSobreActionPerformed(evt);
            }
        });
        jmnSobre.add(jmiSobre);

        jMenuBar1.add(jmnSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMdiFrota, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMdiFrota, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMotoristaActionPerformed
        Motorista CM = new Motorista();
        jdpMdiFrota.add(CM);
        CM.centralizar(jdpMdiFrota);
        CM.setVisible(true);
    }//GEN-LAST:event_jmiMotoristaActionPerformed

    private void jmnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnCadastroActionPerformed

    }//GEN-LAST:event_jmnCadastroActionPerformed

    private void jmiCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCidadeActionPerformed
        Cidade Cid = new Cidade();
        jdpMdiFrota.add(Cid);
        Cid.centralizar(jdpMdiFrota);
        Cid.setVisible(true);
    }//GEN-LAST:event_jmiCidadeActionPerformed

    private void jmiVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVeiculoActionPerformed
        Veiculo Vei = new Veiculo();
        jdpMdiFrota.add(Vei);
        Vei.centralizar(jdpMdiFrota);
        Vei.setVisible(true);
    }//GEN-LAST:event_jmiVeiculoActionPerformed

    private void jmiEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEstadoActionPerformed
        Estado UF = new Estado();
        jdpMdiFrota.add(UF);
        UF.centralizar(jdpMdiFrota);
        UF.setVisible(true);
    }//GEN-LAST:event_jmiEstadoActionPerformed

    private void jmiMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMarcaActionPerformed
        Marca Ma = new Marca();
        jdpMdiFrota.add(Ma);
        Ma.centralizar(jdpMdiFrota);
        Ma.setVisible(true);
    }//GEN-LAST:event_jmiMarcaActionPerformed

    private void jmiModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModeloActionPerformed
        Modelo Mo = new Modelo();
        jdpMdiFrota.add(Mo);
        Mo.centralizar(jdpMdiFrota);
        Mo.setVisible(true);
    }//GEN-LAST:event_jmiModeloActionPerformed

    private void jmiMovFrotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMovFrotaActionPerformed
        Movimentacao Mov = new Movimentacao();
        jdpMdiFrota.add(Mov);
        Mov.centralizar(jdpMdiFrota);
        Mov.setVisible(true);
    }//GEN-LAST:event_jmiMovFrotaActionPerformed

    private void jmiEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEventosActionPerformed
        Evento Eve = new Evento();
        jdpMdiFrota.add(Eve);
        Eve.centralizar(jdpMdiFrota);
        Eve.setVisible(true);
    }//GEN-LAST:event_jmiEventosActionPerformed

    private void jmiEventosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEventosItemActionPerformed
        Evento_Item Evi = new Evento_Item();
        jdpMdiFrota.add(Evi);
        Evi.centralizar(jdpMdiFrota);
        Evi.setVisible(true);
    }//GEN-LAST:event_jmiEventosItemActionPerformed

    private void jmiFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedoresActionPerformed
        CadFornecedores For = new CadFornecedores();
        jdpMdiFrota.add(For);
        For.centralizar(jdpMdiFrota);
        For.setVisible(true);
    }//GEN-LAST:event_jmiFornecedoresActionPerformed

    private void jmiChavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiChavesActionPerformed
        Chaves Cha = new Chaves();
        jdpMdiFrota.add(Cha);
        Cha.centralizar(jdpMdiFrota);
        Cha.setVisible(true);
    }//GEN-LAST:event_jmiChavesActionPerformed

    private void jmiDevolucaoChavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDevolucaoChavesActionPerformed
        ChavesDevolucao ChaD = new ChavesDevolucao();
        jdpMdiFrota.add(ChaD);
        ChaD.centralizar(jdpMdiFrota);
        ChaD.setVisible(true);
    }//GEN-LAST:event_jmiDevolucaoChavesActionPerformed

    private void jmiInfracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInfracoesActionPerformed
        Infracoes Inf = new Infracoes();
        jdpMdiFrota.add(Inf);
        Inf.centralizar(jdpMdiFrota);
        Inf.setVisible(true);
    }//GEN-LAST:event_jmiInfracoesActionPerformed

    private void jmiLancamentoMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLancamentoMultasActionPerformed
        Multa Mul = new Multa();
        jdpMdiFrota.add(Mul);
        Mul.centralizar(jdpMdiFrota);
        Mul.setVisible(true);
    }//GEN-LAST:event_jmiLancamentoMultasActionPerformed

    private void jmiRankingMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRankingMultasActionPerformed
        Pontos Pon = new Pontos();
        jdpMdiFrota.add(Pon);
        Pon.centralizar(jdpMdiFrota);
        Pon.setVisible(true);
    }//GEN-LAST:event_jmiRankingMultasActionPerformed

    private void jmiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutoActionPerformed
        Produto Pro = new Produto();
        jdpMdiFrota.add(Pro);
        Pro.centralizar(jdpMdiFrota);
        Pro.setVisible(true);
    }//GEN-LAST:event_jmiProdutoActionPerformed

    private void jmiNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNFActionPerformed
        NotaFiscal NF = new NotaFiscal();
        jdpMdiFrota.add(NF);
        NF.centralizar(jdpMdiFrota);
        NF.setVisible(true);
    }//GEN-LAST:event_jmiNFActionPerformed

    private void jmiRastrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRastrearActionPerformed
        Rastrear Ra = new Rastrear();
        jdpMdiFrota.add(Ra);
        Ra.centralizar(jdpMdiFrota);
        Ra.setVisible(true);
    }//GEN-LAST:event_jmiRastrearActionPerformed

    private void jmnVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnVeiculoActionPerformed
        ConsultaVeiculo CV = new ConsultaVeiculo();
        jdpMdiFrota.add(CV);
        CV.centralizar(jdpMdiFrota);
        CV.setVisible(true);
    }//GEN-LAST:event_jmnVeiculoActionPerformed

    private void jmiConsultaMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaMotoristaActionPerformed
        ConsultaMotorista CM = new ConsultaMotorista();
        jdpMdiFrota.add(CM);
        CM.centralizar(jdpMdiFrota);
        CM.setVisible(true);
    }//GEN-LAST:event_jmiConsultaMotoristaActionPerformed

    private void jmiImpressaoMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImpressaoMotoristaActionPerformed
        ImpressaoMotorista IM = new ImpressaoMotorista();
        jdpMdiFrota.add(IM);
        IM.centralizar(jdpMdiFrota);
        IM.setVisible(true);
    }//GEN-LAST:event_jmiImpressaoMotoristaActionPerformed

    private void jmiImpressaoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImpressaoVeiculoActionPerformed
        ImpressaoVeiculo IV = new ImpressaoVeiculo();
        jdpMdiFrota.add(IV);
        IV.centralizar(jdpMdiFrota);
        IV.setVisible(true);
    }//GEN-LAST:event_jmiImpressaoVeiculoActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
        ImpressaoFornecedor IF = new ImpressaoFornecedor();
        jdpMdiFrota.add(IF);
        IF.centralizar(jdpMdiFrota);
        IF.setVisible(true);
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        Sobre So = new Sobre();
        jdpMdiFrota.add(So);
        So.centralizar(jdpMdiFrota);
        So.setVisible(true);
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void jmiImpressaoNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImpressaoNFActionPerformed
        ImpressaoNotaFiscal NF = new ImpressaoNotaFiscal();
        jdpMdiFrota.add(NF);
        NF.centralizar(jdpMdiFrota);
        NF.setVisible(true);
    }//GEN-LAST:event_jmiImpressaoNFActionPerformed

    private void jmiCarroceriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCarroceriaActionPerformed
        Carroceria Carr = new Carroceria();
        jdpMdiFrota.add(Carr);
        Carr.centralizar(jdpMdiFrota);
        Carr.setVisible(true);
    }//GEN-LAST:event_jmiCarroceriaActionPerformed

    private void jmiCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCategoriaActionPerformed
        Categoria Cat = new Categoria();
        jdpMdiFrota.add(Cat);
        Cat.centralizar(jdpMdiFrota);
        Cat.setVisible(true);
    }//GEN-LAST:event_jmiCategoriaActionPerformed

    private void jmiCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCombustivelActionPerformed
        Combustivel Comb = new Combustivel();
        jdpMdiFrota.add(Comb);
        Comb.centralizar(jdpMdiFrota);
        Comb.setVisible(true);
    }//GEN-LAST:event_jmiCombustivelActionPerformed

    private void jmiCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCorActionPerformed
        Cor Cor = new Cor();
        jdpMdiFrota.add(Cor);
        Cor.centralizar(jdpMdiFrota);
        Cor.setVisible(true);
    }//GEN-LAST:event_jmiCorActionPerformed

    private void jmiEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEspecieActionPerformed
        Especie Esp = new Especie();
        jdpMdiFrota.add(Esp);
        Esp.centralizar(jdpMdiFrota);
        Esp.setVisible(true);
    }//GEN-LAST:event_jmiEspecieActionPerformed

    private void jmiRestricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRestricaoActionPerformed
        Restricao Res = new Restricao();
        jdpMdiFrota.add(Res);
        Res.centralizar(jdpMdiFrota);
        Res.setVisible(true);
    }//GEN-LAST:event_jmiRestricaoActionPerformed

    private void jmiImpressaoMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImpressaoMovimentacaoActionPerformed
        ImpressaoMovimentacao Mov = new ImpressaoMovimentacao();
        jdpMdiFrota.add(Mov);
        Mov.centralizar(jdpMdiFrota);
        Mov.setVisible(true);
    }//GEN-LAST:event_jmiImpressaoMovimentacaoActionPerformed

    private void jmiHistoricoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHistoricoCarroActionPerformed
        ImpressaoHistoricoCarro IHC = new ImpressaoHistoricoCarro();
        jdpMdiFrota.add(IHC);
        IHC.centralizar(jdpMdiFrota);
        IHC.setVisible(true);
    }//GEN-LAST:event_jmiHistoricoCarroActionPerformed

    private void jmiImpressaoPontuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImpressaoPontuacaoActionPerformed
        ImpressaoPontuacao IP = new ImpressaoPontuacao();
        jdpMdiFrota.add(IP);
        IP.centralizar(jdpMdiFrota);
        IP.setVisible(true);
    }//GEN-LAST:event_jmiImpressaoPontuacaoActionPerformed

    private void jmiRendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRendimentoActionPerformed
        ImpressaoRendimento IR = new ImpressaoRendimento();
        jdpMdiFrota.add(IR);
        IR.centralizar(jdpMdiFrota);
        IR.setVisible(true);
    }//GEN-LAST:event_jmiRendimentoActionPerformed

    private void jmiImpInfraTransitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImpInfraTransitoActionPerformed
        ImpressaoMulta IM = new ImpressaoMulta();
        jdpMdiFrota.add(IM);
        IM.centralizar(jdpMdiFrota);
        IM.setVisible(true);
    }//GEN-LAST:event_jmiImpInfraTransitoActionPerformed

    private void jmiSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSeguroActionPerformed
        Seguro Seg = new Seguro();
        jdpMdiFrota.add(Seg);
        Seg.centralizar(jdpMdiFrota);
        Seg.setVisible(true);
    }//GEN-LAST:event_jmiSeguroActionPerformed

    private void jmiManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManutencaoActionPerformed
        Manutencao Man = new Manutencao();
        jdpMdiFrota.add(Man);
        Man.centralizar(jdpMdiFrota);
        Man.setVisible(true);
    }//GEN-LAST:event_jmiManutencaoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiFrota().setVisible(true);
            }    
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JDesktopPane jdpMdiFrota;
    private javax.swing.JMenuItem jmiCarroceria;
    private javax.swing.JMenuItem jmiCategoria;
    private javax.swing.JMenuItem jmiChaves;
    private javax.swing.JMenuItem jmiCidade;
    private javax.swing.JMenuItem jmiCombustivel;
    private javax.swing.JMenuItem jmiConsultaMotorista;
    private javax.swing.JMenuItem jmiCor;
    private javax.swing.JMenuItem jmiDevolucaoChaves;
    private javax.swing.JMenuItem jmiEspecie;
    private javax.swing.JMenuItem jmiEstado;
    private javax.swing.JMenuItem jmiEventos;
    private javax.swing.JMenuItem jmiEventosItem;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiFornecedores;
    private javax.swing.JMenuItem jmiHistoricoCarro;
    private javax.swing.JMenuItem jmiImpInfraTransito;
    private javax.swing.JMenu jmiImpressaoCarro;
    private javax.swing.JMenuItem jmiImpressaoMotorista;
    private javax.swing.JMenuItem jmiImpressaoMovimentacao;
    private javax.swing.JMenuItem jmiImpressaoNF;
    private javax.swing.JMenuItem jmiImpressaoPontuacao;
    private javax.swing.JMenuItem jmiImpressaoVeiculo;
    private javax.swing.JMenuItem jmiInfracoes;
    private javax.swing.JMenuItem jmiLancamentoMultas;
    private javax.swing.JMenuItem jmiManutencao;
    private javax.swing.JMenuItem jmiMarca;
    private javax.swing.JMenuItem jmiModelo;
    private javax.swing.JMenuItem jmiMotorista;
    private javax.swing.JMenuItem jmiMovFrota;
    private javax.swing.JMenuItem jmiNF;
    private javax.swing.JMenuItem jmiProduto;
    private javax.swing.JMenuItem jmiRankingMultas;
    private javax.swing.JMenuItem jmiRastrear;
    private javax.swing.JMenuItem jmiRendimento;
    private javax.swing.JMenuItem jmiRestricao;
    private javax.swing.JMenuItem jmiSeguro;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiVeiculo;
    private javax.swing.JMenu jmnCadastro;
    private javax.swing.JMenu jmnCarro;
    private javax.swing.JMenu jmnConsulta;
    private javax.swing.JMenu jmnEventos;
    private javax.swing.JMenu jmnFederacoes;
    private javax.swing.JMenu jmnImpressaoCadastro;
    private javax.swing.JMenu jmnImpressaoMovimetacao;
    private javax.swing.JMenu jmnImpressão;
    private javax.swing.JMenu jmnManutencao;
    private javax.swing.JMenu jmnMovimentacao;
    private javax.swing.JMenu jmnMulta;
    private javax.swing.JMenu jmnSobre;
    private javax.swing.JMenu jmnTipoVeiculo;
    private javax.swing.JMenu jmnTipos;
    private javax.swing.JMenuItem jmnVeiculo;
    private javax.swing.JMenu jmuImpressaoMulta;
    // End of variables declaration//GEN-END:variables

}
