/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadFornecedores.java
 *
 * Created on 24/11/2009, 07:27:00
 */

package controle;

import classes.ConexaoAccess;
import classes.Funcoes;
import classes.ValidaDocumentos;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeferson
 */
public class CadFornecedores extends javax.swing.JInternalFrame {

    private ConexaoAccess Conexao;
    private Funcoes Fun;
    private ValidaDocumentos VD;

    /** Creates new form CadFornecedores */
    public CadFornecedores() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbFone1 = new javax.swing.JLabel();
        jtfCep = new javax.swing.JTextField();
        jlbCep = new javax.swing.JLabel();
        jtfCidade_Cod = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jlbCidade = new javax.swing.JLabel();
        jlbFone2 = new javax.swing.JLabel();
        jlbFax = new javax.swing.JLabel();
        jlbIM = new javax.swing.JLabel();
        jtfIm = new javax.swing.JTextField();
        jtfIe = new javax.swing.JTextField();
        jlbIE = new javax.swing.JLabel();
        jlbContato = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jtfCnpjCpf = new javax.swing.JTextField();
        jlbCnpj_Cpf = new javax.swing.JLabel();
        jlbBairro = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jtfFantasia = new javax.swing.JTextField();
        jlbFantasia = new javax.swing.JLabel();
        jlbNome = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jlbEndereco = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfNomeCidade = new javax.swing.JTextField();
        jtfContato = new javax.swing.JTextField();
        jtfFax = new javax.swing.JFormattedTextField();
        jtfFone1 = new javax.swing.JFormattedTextField();
        jtfFone2 = new javax.swing.JFormattedTextField();
        jbtNovo = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Cadastro de Fornecedores");

        jlbFone1.setText("Fone 1");

        jlbCep.setText("CEP");

        jtfCidade_Cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCidade_CodKeyPressed(evt);
            }
        });

        jlbCidade.setText("Cidade");

        jlbFone2.setText("Fone 2");

        jlbFax.setText("Fax");

        jlbIM.setText("Inscrição Municipal");

        jlbIE.setText("Inscrição Estadual");

        jlbContato.setText("Contato");

        jlbEmail.setText("E-mail");

        jtfCnpjCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCnpjCpfActionPerformed(evt);
            }
        });
        jtfCnpjCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCnpjCpfKeyPressed(evt);
            }
        });

        jlbCnpj_Cpf.setText("CNPJ/CPF");

        jlbBairro.setText("Bairro");

        jlbFantasia.setText("Nome Fantasia");

        jlbNome.setText("Nome");

        jlbEndereco.setText("Endereço");

        jtfFax.setFormatterFactory(Fun.setFormatoTelefone());

        jtfFone1.setFormatterFactory(Fun.setFormatoTelefone());

        jtfFone2.setFormatterFactory(Fun.setFormatoTelefone());

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbBairro)
                        .addGap(201, 201, 201)
                        .addComponent(jlbCidade))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbFantasia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEndereco)
                            .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCnpjCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCnpj_Cpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                            .addComponent(jlbNome)))
                    .addComponent(jlbEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbIM)
                            .addComponent(jtfIm, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfIe, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbIE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbContato)
                                .addGap(20, 20, 20))
                            .addComponent(jtfContato, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                    .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCidade_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbCep)
                                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfFone1)
                                    .addComponent(jlbFone1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbFone2)
                                    .addComponent(jtfFone2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbFax)
                                    .addComponent(jtfFax, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jtfNomeCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCnpj_Cpf)
                    .addComponent(jlbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCnpjCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbFantasia)
                    .addComponent(jlbEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBairro)
                    .addComponent(jlbCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidade_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlbCep)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfFone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlbFone1)
                            .addGap(26, 26, 26)))
                    .addComponent(jlbFone2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbFax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbIM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbIE)
                            .addComponent(jlbContato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtSalvar)
                        .addComponent(jbtNovo))
                    .addComponent(jbtExcluir)
                    .addComponent(jbtPesquisar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NovoRegistro(){

        String SQL;

        SQL = "insert into t_fornecedor (cnpjcpf, nomefornecedor, nomefantasia, enderecofornecedor, bairrofornecedor, ";
        SQL = SQL + "cidadecod, cepfornecedor, fone1fornecedor, fone2fornecedor, faxfornecedor, iefornecedor, ";
        SQL = SQL + "imfornecedor, contatofornecedor, emailfornecedor, exclusao) ";
        SQL = SQL + "values ('" + jtfCnpjCpf.getText() + "', '" + jtfNome.getText();
        SQL = SQL + "', '" + jtfFantasia.getText() + "', '" + jtfEndereco.getText() + "', '" + jtfBairro.getText();
        SQL = SQL + "', " + jtfCidade_Cod.getText() + ", '" + jtfCep.getText() + "', '" + jtfFone1.getText() + "', '";
        SQL = SQL + jtfFone2.getText() + "', '" + jtfFax.getText() + "', '" + jtfIe.getText() + "', '";
        SQL = SQL + jtfIm.getText() + "', '" + jtfContato.getText() + "', '" + jtfEmail.getText() + "', 0)";
        
        Conexao.setSQL(SQL);
        Conexao.Executar();

    }

    private void jtfCnpjCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCnpjCpfKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            CarregarDados(jtfCnpjCpf.getText());

        }

    }//GEN-LAST:event_jtfCnpjCpfKeyPressed

    private void jtfCidade_CodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidade_CodKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Fun = new Funcoes();
            jtfNomeCidade.setText(Fun.NomeCidade(Integer.parseInt(jtfCidade_Cod.getText())));

            jtfCep.requestFocus();
        }

        if(evt.getKeyCode() == KeyEvent.VK_F12){
            SubPesquisaCidade A = new SubPesquisaCidade();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
                A.SetSubPesquisaFornecedores(this);
                A.Validador("Fornecedor");
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
        }
        
    }//GEN-LAST:event_jtfCidade_CodKeyPressed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed

        Limpar();

        jtfCnpjCpf.requestFocus();

    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        Object[] botoes = { "Sim", "Não" };
        
        int resposta;

        resposta = JOptionPane.showOptionDialog(null, "Você deseja realmente excluir este registro?", "Confirma exclusão", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

        if(resposta == JOptionPane.YES_OPTION){

            String SQL = "update t_fornecedor set exclusao = 1 where cnpjcpf = '" + jtfCnpjCpf.getText() + "'";         

            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL(SQL);
            Conexao.Executar();
            Conexao.Desconectar();

            Limpar();

        }

        jtfCnpjCpf.requestFocus();

    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed

        PesquisaFornecedores A = new PesquisaFornecedores();
        A.setVisible(true);
        JDesktopPane JDP = this.getDesktopPane();
        JDP.add(A);
        A.centralizar(JDP);
        try{
            A.setSelected(true);
            A.SetFornecedor(this);
        }catch (Exception E){
            JOptionPane.showMessageDialog(null, "Erro: " + E);
        }
        A.setVisible(true);

    }//GEN-LAST:event_jbtPesquisarActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        Conexao = new ConexaoAccess();
        Conexao.Conectar();
        Conexao.setSQL("select * from t_fornecedor where cnpjcpf = '" + jtfCnpjCpf.getText() + "' ");
        ResultSet RS = Conexao.Consultar();

        try {
            if(RS.next()){
                String SQL;

                SQL = "update t_fornecedor set nomefornecedor = '" + jtfNome.getText() + "', nomefantasia = '";
                SQL = SQL + jtfFantasia.getText() + "', enderecofornecedor = '" + jtfEndereco.getText();
                SQL = SQL + "', bairrofornecedor = '" + jtfBairro.getText() + "', " + "cidadecod = " + jtfCidade_Cod.getText() ;
                SQL = SQL + ", cepfornecedor = '" + jtfCep.getText() + "', fone1fornecedor = '" + jtfFone1.getText();
                SQL = SQL + "', fone2fornecedor = '" + jtfFone2.getText() + "', faxfornecedor = '" + jtfFax.getText();
                SQL = SQL + "', iefornecedor = '" + jtfIe.getText() + "', imfornecedor = '";
                SQL = SQL + jtfIm.getText() + "', contatofornecedor = '" + jtfContato.getText() + "', emailfornecedor = '" + jtfEmail.getText() + "' ";
                SQL = SQL + "where cnpjcpf = '" + jtfCnpjCpf.getText() + "'";

                Conexao.setSQL(SQL);
                Conexao.Executar();
            } else {
                
                Object[] botoes = { "Sim", "Não" }; 

                if (jtfCnpjCpf.getText().length() == 11) {

                    VD = new ValidaDocumentos();

                    if (!(VD.validaCPF(jtfCnpjCpf.getText()))) {

                        int resposta;

                        resposta = JOptionPane.showOptionDialog(null, "CNPJ inválido! deseja continuar", "Opaaaaa!!!", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

                        if(resposta == JOptionPane.YES_OPTION){

                            NovoRegistro();

                        }

                    } else {

                        NovoRegistro();

                    }
                
                } else {

                    VD = new ValidaDocumentos();

                    if (!(VD.validaCNPJ(jtfCnpjCpf.getText()))) {

                        int resposta;

                        resposta = JOptionPane.showOptionDialog(null, "CNPJ inválido! deseja continuar", "Opaaaaa!!!", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

                        if(resposta == JOptionPane.YES_OPTION){

                            NovoRegistro();

                        }
                        
                    } else {

                        NovoRegistro();
                        
                    }
                }
            }
        } catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();

        Limpar();

        jtfCnpjCpf.requestFocus();

    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jtfCnpjCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCnpjCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCnpjCpfActionPerformed

    public void CarregarDados(String Codigo){

        String SQL;

        SQL = "select * from t_fornecedor ";
        SQL = SQL + "where cnpjcpf = '" + Codigo + "' ";
        SQL = SQL + "and exclusao = 0 ";

        Conexao = new ConexaoAccess();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ResultSet RS = Conexao.Consultar();

        try{
            if (RS.next()){
                jtfCnpjCpf.setText(RS.getString("cnpjcpf"));
                jtfNome.setText(RS.getString("nomefornecedor"));
                jtfFantasia.setText(RS.getString("nomefantasia"));
                jtfEndereco.setText(RS.getString("enderecofornecedor"));
                jtfBairro.setText(RS.getString("bairrofornecedor"));
                jtfCidade_Cod.setText(RS.getString("cidadecod"));

                Fun = new Funcoes();
                jtfNomeCidade.setText(Fun.NomeCidade(Integer.parseInt(RS.getString("cidadecod"))));

                jtfCep.setText(RS.getString("cepfornecedor"));
                jtfFone1.setText(RS.getString("fone1fornecedor"));
                jtfFone2.setText(RS.getString("fone2fornecedor"));
                jtfFax.setText(RS.getString("faxfornecedor"));
                jtfIe.setText(RS.getString("iefornecedor"));
                jtfIm.setText(RS.getString("imfornecedor"));
                jtfContato.setText(RS.getString("contatofornecedor"));
                jtfEmail.setText(RS.getString("emailfornecedor"));
            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();

        jtfNome.requestFocus();

    }

    public void PuxaCidade(int Codigo){

        String SQL;

        SQL = "select cid.codcidade, cid.cidade, cid.coduf, cuf.uf ";
        SQL = SQL + "from cidade cid ";
        SQL = SQL + "inner join cidade_uf cuf on cuf.coduf = cid.coduf ";
        SQL = SQL + "where cid.codcidade = " + Codigo + " ";
        SQL = SQL + "and cid.exclusao = 0 ";

        Conexao = new ConexaoAccess();
        Conexao.Conectar();
        Conexao.setSQL(SQL);

        ResultSet RS = Conexao.Consultar();

        try{
            if (RS.next()){

                jtfCidade_Cod.setText(RS.getString("codcidade"));
                jtfNomeCidade.setText(RS.getString("cidade"));

            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JLabel jlbBairro;
    private javax.swing.JLabel jlbCep;
    private javax.swing.JLabel jlbCidade;
    private javax.swing.JLabel jlbCnpj_Cpf;
    private javax.swing.JLabel jlbContato;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbEndereco;
    private javax.swing.JLabel jlbFantasia;
    private javax.swing.JLabel jlbFax;
    private javax.swing.JLabel jlbFone1;
    private javax.swing.JLabel jlbFone2;
    private javax.swing.JLabel jlbIE;
    private javax.swing.JLabel jlbIM;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCidade_Cod;
    private javax.swing.JTextField jtfCnpjCpf;
    private javax.swing.JTextField jtfContato;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfFantasia;
    private javax.swing.JFormattedTextField jtfFax;
    private javax.swing.JFormattedTextField jtfFone1;
    private javax.swing.JFormattedTextField jtfFone2;
    private javax.swing.JTextField jtfIe;
    private javax.swing.JTextField jtfIm;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNomeCidade;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFornecedores().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    private void Limpar(){

        jtfCnpjCpf.setText("");
        jtfNome.setText("");
        jtfFantasia.setText("");
        jtfEndereco.setText("");
        jtfBairro.setText("");
        jtfCidade_Cod.setText("");
        jtfNomeCidade.setText("");
        jtfCep.setText("");
        jtfFone1.setText("");
        jtfFone2.setText("");
        jtfFax.setText("");
        jtfIm.setText("");
        jtfIe.setText("");
        jtfContato.setText("");
        jtfEmail.setText("");
        
    }
   
}
