/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Motorista.java
 *
 * Created on 06/10/2009, 11:13:34
 */

package controle;

import classes.ConexaoAccess;
import classes.Funcoes;
import classes.ValidaDocumentos;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Jeferson
 */
public class Motoristabkp extends javax.swing.JInternalFrame {
    
    private ConexaoAccess Conexao;
    private Funcoes Fun;
    private ValidaDocumentos VD;
    public String Resultado;
    boolean Tela = false;

    /** Creates new form Motorista */
    public Motoristabkp() {             
      
        try {            
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());  
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e){            
            e.printStackTrace();            
        }
        
        initComponents();
        form(Tela);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfCpf = new javax.swing.JTextField();
        jlbCpf = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jtfCep = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jtfRg = new javax.swing.JTextField();
        jtfCnh = new javax.swing.JTextField();
        jlbNome = new javax.swing.JLabel();
        jlbEndereco = new javax.swing.JLabel();
        jlbBairro = new javax.swing.JLabel();
        jlbCep = new javax.swing.JLabel();
        jlbCidade = new javax.swing.JLabel();
        jlbRg = new javax.swing.JLabel();
        jlbCnh = new javax.swing.JLabel();
        jlbValCnh = new javax.swing.JLabel();
        jtfCidadeCod = new javax.swing.JTextField();
        jtfFone = new javax.swing.JFormattedTextField();
        jlbFone = new javax.swing.JLabel();
        jlbCelular = new javax.swing.JLabel();
        jtfCelular = new javax.swing.JFormattedTextField();
        jlbDtNasc = new javax.swing.JLabel();
        jtfDtNasc = new javax.swing.JFormattedTextField();
        jtfValCnh = new javax.swing.JFormattedTextField();
        jbtExcluir = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();
        jbtNovo = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Motorista");

        jtfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCpfActionPerformed(evt);
            }
        });
        jtfCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCpfKeyPressed(evt);
            }
        });

        jlbCpf.setText("CPF");

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        jtfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEnderecoActionPerformed(evt);
            }
        });

        jtfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCidadeKeyPressed(evt);
            }
        });

        jlbNome.setText("Nome");

        jlbEndereco.setText("Endereço");

        jlbBairro.setText("Bairro");

        jlbCep.setText("CEP");

        jlbCidade.setText("Cidade (F12)");

        jlbRg.setText("RG");

        jlbCnh.setText("CNH");

        jlbValCnh.setText("Val.CNH");

        jtfCidadeCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCidadeCodActionPerformed(evt);
            }
        });
        jtfCidadeCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCidadeCodKeyPressed(evt);
            }
        });

        jtfFone.setFormatterFactory(Fun.setFormatoTelefone());
        jtfFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFoneActionPerformed(evt);
            }
        });

        jlbFone.setText("Telefone");

        jlbCelular.setText("Celular");

        jtfCelular.setFormatterFactory(Fun.setFormatoTelefone());

        jlbDtNasc.setText("Data de Nascimento");

        jtfDtNasc.setFormatterFactory(Fun.setFormatoData());

        jtfValCnh.setFormatterFactory(Fun.setFormatoData());

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNome)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlbEndereco)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                            .addComponent(jlbBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCep)
                            .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfCidadeCod, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                    .addComponent(jlbCidade)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfRg, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(jlbRg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCnh)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCnh)
                                .addGap(169, 169, 169)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbValCnh)
                            .addComponent(jtfValCnh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbFone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDtNasc)
                            .addComponent(jlbDtNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCpf)
                    .addComponent(jlbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBairro)
                    .addComponent(jlbCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCidadeCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbFone)
                            .addComponent(jlbCelular)
                            .addComponent(jlbDtNasc))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbRg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCnh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfValCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbValCnh)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtSalvar)
                        .addComponent(jbtNovo))
                    .addComponent(jbtExcluir)
                    .addComponent(jbtPesquisar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void CarregarDados(int codigo){
        jtfCpf.setText(Integer.toString(codigo));
    }

    private void jtfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCpfActionPerformed

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jtfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEnderecoActionPerformed

    private void NovoRegistro(String ValCNH, String Data){

        String SQL;
        SQL = "insert into t_motorista (cpf, nome, endereco, bairro, cep, cidade, rg, cnh, val_cnh, telefone, celular, data_nascimento, exclusao";
        SQL = SQL + ") values('";
        SQL = SQL + jtfCpf.getText() + "', '" + jtfNome.getText() + "', '" + jtfEndereco.getText() + "', '";
        SQL = SQL + jtfBairro.getText() + "', '" + jtfCep.getText() + "', " + jtfCidadeCod.getText() + ", '";
        SQL = SQL + jtfRg.getText() + "', '" + jtfCnh.getText() + "', " + ValCNH + ", '" + jtfFone.getText() + "', '";
        SQL = SQL + jtfCelular.getText() + "', " + Data + ", 0)";
        Conexao.setSQL(SQL);
        Conexao.Executar();

    }

    private void jtfCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCpfKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            CarregaDados(jtfCpf.getText());

        }
    }//GEN-LAST:event_jtfCpfKeyPressed


    private void jtfCidadeCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeCodKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            PuxaCidade(Integer.parseInt(jtfCidade.getText()));
        }
        if(evt.getKeyCode() == KeyEvent.VK_F12){
            SubPesquisaCidade A = new SubPesquisaCidade();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
//                A.SetSubCidade(this);
                A.Validador("Motorista");
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
        }
    }//GEN-LAST:event_jtfCidadeCodKeyPressed

    private void jtfCidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_F12){
            SubPesquisaCidade A = new SubPesquisaCidade();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
//                A.SetSubCidade(this);
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
        }
    }//GEN-LAST:event_jtfCidadeKeyPressed

    private void jtfFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFoneActionPerformed

    private void jtfCidadeCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCidadeCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCidadeCodActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        Object[] botoes = { "Sim", "Não" };

        int resposta;

        resposta = JOptionPane.showOptionDialog(null, "Você deseja realmente excluir este registro?", "Confirma exclusão", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

        if(resposta == JOptionPane.YES_OPTION){

            String SQL = "update t_motorista set exclusao = 1 where cpf = '" + jtfCpf.getText() + "'";

            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL(SQL);
            Conexao.Executar();
            Conexao.Desconectar();

            Limpar();

        }

        jtfCpf.requestFocus();

    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        Conexao = new ConexaoAccess();
        Conexao.Conectar();
        Conexao.setSQL("select * from T_Motorista where cpf = '" + jtfCpf.getText() + "' ");
        ResultSet RS = Conexao.Consultar();

        try {
            
            Fun = new Funcoes();
            String Data;

            if (!(Fun.isValidDate(jtfDtNasc.getText()))){
                Data = null;
            } else {
                Data = jtfDtNasc.getText();
            }

            Fun = new Funcoes();
            String val_cnh;

            if (!(Fun.isValidDate(jtfValCnh.getText()))){
                val_cnh = null;
            } else {
                val_cnh = jtfDtNasc.getText();
            }
            
            if(RS.next()){
                String SQL;
                SQL = "update t_motorista set nome = '" + jtfNome.getText() + "', endereco = '" + jtfEndereco.getText();
                SQL = SQL + "', bairro = '" + jtfBairro.getText() + "', cep = '" + jtfCep.getText() + "', cidade = ";
                SQL = SQL + jtfCidadeCod.getText() + ", rg = '" + jtfRg.getText() + "', cnh = '" + jtfCnh.getText();
                SQL = SQL + "', val_cnh = " + val_cnh + ", telefone = '" + jtfFone.getText() + "', ";
                SQL = SQL + "celular = '" + jtfCelular.getText() + "', data_nascimento = " + Data;
                SQL = SQL + " where cpf = '" + jtfCpf.getText() + "'";
                Conexao.setSQL(SQL);
                Conexao.Executar();
            } else {
                Object[] botoes = { "Sim", "Não" };

                VD = new ValidaDocumentos();

                if (!(VD.validaCPF(jtfCpf.getText()))) {

                    int resposta;

                    resposta = JOptionPane.showOptionDialog(null, "CNPJ inválido! deseja continuar", "Opaaaaa!!!", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

                    if(resposta == JOptionPane.YES_OPTION){

                        NovoRegistro(val_cnh, Data);

                    }

                } else {

                    NovoRegistro(val_cnh, Data);

                }

            }

        } catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();

        Limpar();

        jtfCpf.requestFocus();

    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed

        PesquisaMotorista A = new PesquisaMotorista();
        A.setVisible(true);
        JDesktopPane JDP = this.getDesktopPane();
        JDP.add(A);
        A.centralizar(JDP);
        try{
            A.setSelected(true);
//            A.SetMotorista(this);
        }catch (Exception E){
            JOptionPane.showMessageDialog(null, "Erro: " + E);
        }
        A.setVisible(true);

    }//GEN-LAST:event_jbtPesquisarActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed

        Limpar();

        jtfCpf.requestFocus();

    }//GEN-LAST:event_jbtNovoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Motoristabkp().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }    

    public void CarregaDados(String Codigo){

        String SQL;
        SQL = "select *, to_char(val_cnh,'DD/MM/YYYY') as val_cnh2, to_char(data_nascimento,'DD/MM/YYYY') as dtnasc ";
        SQL = SQL + "from t_motorista where CPF = '" + Codigo + "' and exclusao = 0 ";
        Conexao = new ConexaoAccess();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ResultSet RS = Conexao.Consultar();

        try{
            if (RS.next()){
                jtfCpf.setText(RS.getString("cpf"));
                jtfBairro.setText(RS.getString("bairro"));
                jtfCep.setText(RS.getString("cep"));
                jtfCidadeCod.setText(RS.getString("cidade"));
                Fun = new Funcoes();
                jtfCidade.setText(Fun.NomeCidade(Integer.parseInt(RS.getString("cidade"))));
                jtfCnh.setText(RS.getString("cnh"));
                jtfEndereco.setText(RS.getString("endereco"));
                jtfNome.setText(RS.getString("Nome"));
                jtfRg.setText(RS.getString("rg"));
                jtfValCnh.setText(RS.getString("val_cnh2"));
                jtfFone.setText(RS.getString("telefone"));
                jtfCelular.setText(RS.getString("celular"));
                jtfDtNasc.setText(RS.getString("dtnasc"));
            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validaçãoxxx: " + Erro);
        }
        jtfNome.requestFocus();
        Conexao.Desconectar();

    }

    public void PuxaCidade(int Codigo){
        
        String SQL;

        SQL = "select cid.codcidade, cid.cidade, cid.coduf, cuf.uf ";
        SQL = SQL + "from cidade cid ";
        SQL = SQL + "inner join cidade_uf cuf on cuf.coduf = cid.coduf ";
        SQL = SQL + "where cid.codcidade = " + Codigo + " ";
        SQL = SQL + "and cid.exclusao = 0 ";

        Conexao = new ConexaoAccess();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ResultSet RS = Conexao.Consultar();

        try{
            if (RS.next()){

                jtfCidadeCod.setText(RS.getString("codcidade"));
                jtfCidade.setText(RS.getString("cidade"));
                
            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

    }

    private boolean form (boolean valor){

        boolean verifica = false;

            if (valor) {
                this.dispose();
                Tela = true;
            }

        return verifica;

    }

    private void Limpar(){

        jtfBairro.setText("");
        jtfCep.setText("");
        jtfCidade.setText("");
        jtfCidadeCod.setText("");
        jtfCnh.setText("");
        jtfCpf.setText("");
        jtfEndereco.setText("");
        jtfNome.setText("");
        jtfRg.setText("");
        jtfValCnh.setText("");
        jtfFone.setText("");
        jtfCelular.setText("");
        jtfDtNasc.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JLabel jlbBairro;
    private javax.swing.JLabel jlbCelular;
    private javax.swing.JLabel jlbCep;
    private javax.swing.JLabel jlbCidade;
    private javax.swing.JLabel jlbCnh;
    private javax.swing.JLabel jlbCpf;
    private javax.swing.JLabel jlbDtNasc;
    private javax.swing.JLabel jlbEndereco;
    private javax.swing.JLabel jlbFone;
    private javax.swing.JLabel jlbNome;
    private javax.swing.JLabel jlbRg;
    private javax.swing.JLabel jlbValCnh;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JFormattedTextField jtfCelular;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfCidadeCod;
    private javax.swing.JTextField jtfCnh;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JFormattedTextField jtfDtNasc;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JFormattedTextField jtfFone;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfRg;
    private javax.swing.JFormattedTextField jtfValCnh;
    // End of variables declaration//GEN-END:variables

}
