/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChavesDevolucao.java
 *
 * Created on 04/12/2009, 14:53:39
 */

package controle;

import classes.Combo;
import classes.ConexaoAccess;
import classes.Funcoes;
import java.awt.Dimension;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeferson
 */
public class ChavesDevolucao extends javax.swing.JInternalFrame {

    private ConexaoAccess Conexao;
    private Funcoes Fun;

    /** Creates new form ChavesDevolucao */
    public ChavesDevolucao() {
        initComponents();
        JogarVeiculo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbVeiculo = new javax.swing.JLabel();
        cboVeiculo = new javax.swing.JComboBox();
        jlbMotorista = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JTextField();
        jtfMotorista = new javax.swing.JTextField();
        jtfHora = new javax.swing.JFormattedTextField();
        jtfKm = new javax.swing.JTextField();
        jtfData = new javax.swing.JFormattedTextField();
        jlbDataInicial = new javax.swing.JLabel();
        jlbKmInicial = new javax.swing.JLabel();
        jlbHoraSaida = new javax.swing.JLabel();
        jlbCodigoSaida = new javax.swing.JLabel();
        jlbCodigo = new javax.swing.JLabel();
        jbtSalvar3 = new javax.swing.JButton();
        jbtNovo = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Devolução da Chave");

        jlbVeiculo.setText("Veículo");

        cboVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboVeiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboVeiculoItemStateChanged(evt);
            }
        });
        cboVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVeiculoActionPerformed(evt);
            }
        });

        jlbMotorista.setText("Motorista");

        jtfHora.setFormatterFactory(Fun.setFormatoHora());

        jtfData.setFormatterFactory(Fun.setFormatoData());

        jlbDataInicial.setText("Data Devolução");

        jlbKmInicial.setText("Km Devolução");

        jlbHoraSaida.setText("Hora Devolução");

        jlbCodigoSaida.setText("Nº saída");

        jlbCodigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jbtSalvar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        jbtSalvar3.setText("Salvar");
        jbtSalvar3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSalvar3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSalvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvar3ActionPerformed(evt);
            }
        });

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbVeiculo)
                            .addComponent(cboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCodigoSaida)))
                    .addComponent(jlbMotorista)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtNovo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtSalvar3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtExcluir))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbDataInicial)
                                        .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtfCpf)
                                    .addGap(10, 10, 10)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbKmInicial)
                                        .addComponent(jtfKm, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbHoraSaida)
                                        .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jtfMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbVeiculo)
                    .addComponent(jlbCodigoSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMotorista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfMotorista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbDataInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbKmInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbHoraSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtSalvar3)
                        .addComponent(jbtNovo))
                    .addComponent(jbtExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboVeiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboVeiculoItemStateChanged
        if (cboVeiculo.getItemCount()>0){
            DadosMotorista();
        }
    }//GEN-LAST:event_cboVeiculoItemStateChanged

    private void cboVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboVeiculoActionPerformed

    private void jbtSalvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvar3ActionPerformed

        //String Veiculo = ((Combo)cboVeiculo.getSelectedItem()).getKey();

        Conexao = new ConexaoAccess();
        Conexao.Conectar();

        String sSQL = "select * from t_chaves_devolucao where codigo = " + jlbCodigo.getText() + "";
        Conexao.setSQL(sSQL);
        ResultSet RS = Conexao.Consultar();

        try {

            Fun = new Funcoes();
            String Data;

            if (!(Fun.isValidDate(jtfData.getText()))){
                Data = null;
            } else {
                Data = "'" + jtfData.getText() + "'";
            }

            Fun = new Funcoes();
            String Hora;

            if (!(Fun.isValidTime(jtfHora.getText()))){
                Hora = null;
            } else {
                Hora = "'" + jtfHora.getText() + "'";
            }

            if(RS.next()){
                String SQL;

                SQL = "insert into t_chaves_devolucao (codigo, km, data, hora, exclusao) values (";
                SQL = SQL + jlbCodigo.getText() + ", '" + jtfKm.getText() + "";
                SQL = SQL + "', " + Data + ", " + Hora + ", 0)";

                Conexao.setSQL(SQL);
                Conexao.Executar();
            }
            
        } catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "(Erro na validação): " + Erro);
        }

        Conexao.Desconectar();

        Limpar();

        cboVeiculo.requestFocus();

        JogarVeiculo();
        
    }//GEN-LAST:event_jbtSalvar3ActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed

        Limpar();

        cboVeiculo.requestFocus();

    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        Object[] botoes = { "Sim", "Não" };

        int resposta;

        resposta = JOptionPane.showOptionDialog(null, "Você deseja realmente excluir este registro?", "Confirma exclusão", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

        if(resposta == JOptionPane.YES_OPTION){
        
            String SQL = "delete from t_chaves_devolucao where codigo = " + jlbCodigo.getText() + "";

            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL(SQL);
            Conexao.Executar();
            Conexao.Desconectar();

            Limpar();

        }

        cboVeiculo.requestFocus();

    }//GEN-LAST:event_jbtExcluirActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChavesDevolucao().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    private void Limpar(){

        jlbCodigo.setText("");

        cboVeiculo.removeAllItems();
        JogarVeiculo();

        jtfCpf.setText("");
        jtfMotorista.setText("");

        jtfKm.setText("");
        jtfData.setText("");
        jtfHora.setText("");
    }

    private void JogarVeiculo(){
        cboVeiculo.removeAllItems();
        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();

            String SQL;

            SQL = "select (tve.chassis) as codigo, (tve.placa) as nome from t_veiculo tve ";
            SQL = SQL + "where tve.chassis in (select chassis_cod from t_chaves where codigo not in (";
            SQL = SQL + "select codigo from t_chaves_devolucao)) ";
            SQL = SQL + "order by tve.placa ";

            Conexao.setSQL(SQL);
            ResultSet RS = Conexao.Consultar();
            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
            while(RS.next()){
                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
                Modelo.addElement(CB);
            }
            cboVeiculo.setModel(Modelo);
        } catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }
    }

    private void DadosMotorista(){

        String Veiculo = ((Combo)cboVeiculo.getSelectedItem()).getKey();

        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();

            String SQL;

            SQL = "select tmo.cpf, tmo.nome, tch.codigo from t_motorista tmo ";
            SQL = SQL + "inner join t_chaves tch on tch.cpf_cod = tmo.cpf ";
            SQL = SQL + "where tch.chassis_cod = '" + Veiculo + "' ";
            SQL = SQL + "group by tmo.cpf, tmo.nome, tch.codigo ";

            Conexao.setSQL(SQL);
            ResultSet RS = Conexao.Consultar();

            if (RS.next()){
                jtfCpf.setText(RS.getString("cpf"));
                jtfMotorista.setText(RS.getString("nome"));
                jlbCodigo.setText(RS.getString("codigo"));
            }
        }catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboVeiculo;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtSalvar3;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JLabel jlbCodigoSaida;
    private javax.swing.JLabel jlbDataInicial;
    private javax.swing.JLabel jlbHoraSaida;
    private javax.swing.JLabel jlbKmInicial;
    private javax.swing.JLabel jlbMotorista;
    private javax.swing.JLabel jlbVeiculo;
    private javax.swing.JTextField jtfCpf;
    private javax.swing.JFormattedTextField jtfData;
    private javax.swing.JFormattedTextField jtfHora;
    private javax.swing.JTextField jtfKm;
    private javax.swing.JTextField jtfMotorista;
    // End of variables declaration//GEN-END:variables

}
