/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImpressaoFornecedor.java
 *
 * Created on 13/01/2010, 09:09:08
 */

package controle;

import classes.Combo;
import classes.ConexaoAccess;
import java.awt.Dimension;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jeferson
 */
public class ImpressaoFornecedor extends javax.swing.JInternalFrame {

    private ConexaoAccess Conexao;

    /** Creates new form ImpressaoFornecedor */
    public ImpressaoFornecedor() {
        initComponents();
        JogarFornecedor();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImpressaoFornecedor().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbInfo = new javax.swing.JLabel();
        cboFornecedor = new javax.swing.JComboBox();
        chkTodos = new javax.swing.JCheckBox();
        btnImprimir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Impressão de Fornecedor");

        jlbInfo.setText("Selecione o Fornecedor");

        cboFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chkTodos.setText("Imprimir Todos");

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/printer.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTodos)
                            .addComponent(jlbInfo)
                            .addComponent(cboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnImprimir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(chkTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JogarFornecedor(){
        
        cboFornecedor.removeAllItems();
        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();

            String SQL;

            SQL = "select (cnpjcpf) as codigo, (nomefantasia) as nome ";
            SQL = SQL + "from t_fornecedor ";
            SQL = SQL + "where cnpjcpf in (select fornecedor_cod from t_nota_fiscal) ";
            SQL = SQL + "order by nome ";

            Conexao.setSQL(SQL);
            ResultSet RS = Conexao.Consultar();
            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
            while(RS.next()){
                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
                Modelo.addElement(CB);
            }
            cboFornecedor.setModel(Modelo);
        } catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }
        
    }
    
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        
        try {

            String SQL;
            String Fornecedor;

            Fornecedor = ((Combo)cboFornecedor.getSelectedItem()).getKey();;

            SQL = "select tfo.cnpjcpf, tfo.nomefornecedor, tfo.nomefantasia, tfo.enderecofornecedor, tfo.bairrofornecedor, ";
            SQL = SQL + "cid.cidade, tfo.cepfornecedor, tfo.fone1fornecedor, ";
            SQL = SQL + "tfo.fone2fornecedor, tfo.faxfornecedor, tfo.iefornecedor, tfo.imfornecedor,tfo.contatofornecedor, ";
            SQL = SQL + "tfo.emailfornecedor ";
            SQL = SQL + "from t_fornecedor tfo ";
            SQL = SQL + "inner join cidade cid on cid.codcidade = tfo.cidadecod ";
            

            boolean checked = chkTodos.isSelected();

            if (!(checked)) {
                SQL = SQL + "where tfo.cnpjcpf = '" + Fornecedor + "' ";
                SQL = SQL + "order by tfo.nomefornecedor ";
            }

            Conexao.setSQL(SQL);

            JRResultSetDataSource jrRS = new JRResultSetDataSource(Conexao.Consultar());
            InputStream is = getClass().getResourceAsStream("/reports/fornecedor.jasper");

            JasperPrint print = JasperFillManager.fillReport(is, new HashMap(), jrRS);
            JasperViewer viewer = new JasperViewer(print, false);

            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewer.setVisible(true);

        } catch (Exception Erro) {
            JOptionPane.showMessageDialog(null, "Erro na busca: " + Erro);
        }

    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox cboFornecedor;
    private javax.swing.JCheckBox chkTodos;
    private javax.swing.JLabel jlbInfo;
    // End of variables declaration//GEN-END:variables

}