/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Infracoes.java
 *
 * Created on 07/12/2009, 16:59:47
 */

package controle;

import classes.ConexaoAccess;
import classes.Funcoes;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import java.text.NumberFormat;

/**
 *
 * @author Jeferson
 */
public class Infracoes extends javax.swing.JInternalFrame {

    private ConexaoAccess Conexao;
    private Funcoes Fun;

    /** Creates new form Infracoes */
    public Infracoes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbCodigo = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jlbDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpDescricao = new javax.swing.JTextPane();
        jlbCompetencia = new javax.swing.JLabel();
        jtfCompetencia = new javax.swing.JTextField();
        jlbGravidade = new javax.swing.JLabel();
        jtfGravidade = new javax.swing.JTextField();
        jtfNomeGravidade = new javax.swing.JTextField();
        jlbUfir = new javax.swing.JLabel();
        jtfUfir = new javax.swing.JTextField();
        jlbReais = new javax.swing.JLabel();
        jftReais = new javax.swing.JFormattedTextField();
        jlbPenalidade = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtpPenalidade = new javax.swing.JTextPane();
        jlbPeso = new javax.swing.JLabel();
        jtfPeso = new javax.swing.JTextField();
        jlbPontos = new javax.swing.JLabel();
        jtfPontos = new javax.swing.JTextField();
        jbtNovo = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Pontuação de Trânsito");

        jlbCodigo.setText("Código");

        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
        });

        jlbDescricao.setText("Descrição");

        jtpDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpDescricaoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtpDescricao);

        jlbCompetencia.setText("Competência");

        jlbGravidade.setText("Gravidade");

        jtfGravidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfGravidadeKeyPressed(evt);
            }
        });

        jlbUfir.setText("Ufir");

        jtfUfir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfUfirKeyPressed(evt);
            }
        });

        jlbReais.setText("R$");

        jlbPenalidade.setText("Penalidade");

        jtpPenalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpPenalidadeKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jtpPenalidade);

        jlbPeso.setText("Peso");

        jtfPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesoKeyPressed(evt);
            }
        });

        jlbPontos.setText("Pontos");

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                    .addComponent(jlbDescricao)
                    .addComponent(jlbPenalidade)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCompetencia)
                            .addComponent(jtfCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPontos)
                            .addComponent(jtfPontos, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfGravidade, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(jlbGravidade, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomeGravidade, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfUfir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbUfir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPeso)
                            .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbReais)
                            .addComponent(jftReais, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbCompetencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbPenalidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbGravidade)
                            .addComponent(jlbPontos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfGravidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNomeGravidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbUfir)
                            .addComponent(jlbPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfUfir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbReais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jftReais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtSalvar)
                        .addComponent(jbtNovo))
                    .addComponent(jbtExcluir)
                    .addComponent(jbtPesquisar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfGravidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfGravidadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            jtfNomeGravidade.setText(NivelMulta(Integer.parseInt(jtfGravidade.getText())));

            jtfNomeGravidade.requestFocus();

        }
    }//GEN-LAST:event_jtfGravidadeKeyPressed

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            CarregaDados(jtfCodigo.getText());
        }

    }//GEN-LAST:event_jtfCodigoKeyPressed

    private void jtfUfirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUfirKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            jtfPeso.requestFocus();

        }
    }//GEN-LAST:event_jtfUfirKeyPressed

    private void jtfPesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesoKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            int ufir = Integer.parseInt(jtfUfir.getText());
            int peso = Integer.parseInt(jtfPeso.getText());

            jftReais.setText(NumberFormat.getCurrencyInstance().format(PrecoMulta(ufir, peso)));

            jftReais.requestFocus();

        }

    }//GEN-LAST:event_jtfPesoKeyPressed

    private void jtpDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpDescricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB){
            jtpPenalidade.requestFocus();
        }
    }//GEN-LAST:event_jtpDescricaoKeyPressed

    private void jtpPenalidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpPenalidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB){
            jtfPontos.requestFocus();
        }
    }//GEN-LAST:event_jtpPenalidadeKeyPressed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed

        Limpar();

        jtfCodigo.requestFocus();
        
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        Conexao = new ConexaoAccess();
        Conexao.Conectar();

        String sSQL = "select * from t_multa where codigo = '" + jtfCodigo.getText() + "' ";
        System.out.println(sSQL);
        Conexao.setSQL(sSQL);
        ResultSet RS = Conexao.Consultar();

        try {
            if(RS.next()){
                String SQL;

                SQL = "update t_multa set descricao = '" + jtpDescricao.getText() + "', ";
                SQL = SQL + "penalidade = '" + jtpPenalidade.getText() + "', ";
                SQL = SQL + "pontuacao = " + jtfPontos.getText() + ", ";
                SQL = SQL + "competencia = '" + jtfCompetencia.getText() + "', ";
                SQL = SQL + "ufir = " + jtfUfir.getText() + ", ";
                SQL = SQL + "peso = " + jtfPeso.getText() + " ";
                SQL = SQL + "where codigo = '" + jtfCodigo.getText() + "'";

                Conexao.setSQL(SQL);
                Conexao.Executar();
            } else {
                String SQL;               

                SQL = "insert into t_multa (codigo, descricao, penalidade, pontuacao, competencia, ufir, peso, exclusao) values ('";
                SQL = SQL + jtfCodigo.getText() + "', '" + jtpDescricao.getText() + "', '" + jtpPenalidade.getText() + "', '" + jtfPontos.getText() + "', '";
                SQL = SQL + jtfCompetencia.getText() + "', " + jtfUfir.getText() + ", " + jtfPeso.getText() + ", 0)";

                Conexao.setSQL(SQL);
                Conexao.Executar();
            }
        } catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "(Erro na validação): " + Erro);
        }

        Conexao.Desconectar();

        Limpar();

        jtfCodigo.requestFocus();
        
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        Object[] botoes = { "Sim", "Não" };
        
        int resposta;

        resposta = JOptionPane.showOptionDialog(null, "Você deseja realmente excluir este registro?", "Confirma exclusão", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

        if(resposta == JOptionPane.YES_OPTION){        
        
            String SQL = "update t_multa set exclusao = 1 where codigo = '" + jtfCodigo.getText() + "'";

            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL(SQL);
            Conexao.Executar();

            Conexao.Desconectar();

            Limpar();
        
        }

        jtfCodigo.requestFocus();
        
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed

        PesquisaInfracoes A = new PesquisaInfracoes();
        A.setVisible(true);
        JDesktopPane JDP = this.getDesktopPane();
        JDP.add(A);
        A.centralizar(JDP);
        try{
            A.setSelected(true);
            A.SetInfracoes(this);
        }catch (Exception E){
            JOptionPane.showMessageDialog(null, "Erro: " + E);
        }
        A.setVisible(true);
        
    }//GEN-LAST:event_jbtPesquisarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Infracoes().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    private void Limpar(){

        jtfCodigo.setText("");
        jtfCompetencia.setText("");
        jtpDescricao.setText("");
        jtpPenalidade.setText("");
        jtfPontos.setText("");        
        jtfGravidade.setText("");
        jtfNomeGravidade.setText("");
        jtfUfir.setText("");
        jtfPeso.setText("");
        jftReais.setText("");

    }

    private String NivelMulta(int codigo){

        String NM=null;

        Fun = new Funcoes();
        NM = Fun.GravidadeMulta(codigo);

        return NM;

    }

    private double PrecoMulta(int ufir, float peso){

        double preco;

        Fun = new Funcoes();

        preco = Fun.ValorUfir(ufir, peso);

        return preco;
        
    }

    public void CarregaDados(String Codigo){

        String SQL;

        SQL = "select codigo, descricao, penalidade, pontuacao, competencia, ufir, peso ";
        SQL = SQL + "from t_multa ";
        SQL = SQL + "where codigo = '" + Codigo + "' ";
        SQL = SQL + "and exclusao = 0 ";

        Conexao = new ConexaoAccess();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ResultSet RS = Conexao.Consultar();

        try{
            if (RS.next()){

                jtfCodigo.setText(RS.getString("codigo"));
                jtfCompetencia.setText(RS.getString("competencia"));
                jtpDescricao.setText(RS.getString("descricao"));                
                jtpPenalidade.setText(RS.getString("penalidade"));
                jtfPontos.setText(RS.getString("pontuacao"));                
                jtfGravidade.setText(RS.getString("pontuacao"));
                jtfNomeGravidade.setText(NivelMulta(Integer.parseInt(RS.getString("pontuacao"))));
                jtfUfir.setText(RS.getString("ufir"));
                jtfPeso.setText(RS.getString("peso"));

                int ufir = Integer.parseInt(jtfUfir.getText());
                float peso = Float.parseFloat(jtfPeso.getText());

                jftReais.setText(NumberFormat.getCurrencyInstance().format(PrecoMulta(ufir, peso)));

            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JFormattedTextField jftReais;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JLabel jlbCompetencia;
    private javax.swing.JLabel jlbDescricao;
    private javax.swing.JLabel jlbGravidade;
    private javax.swing.JLabel jlbPenalidade;
    private javax.swing.JLabel jlbPeso;
    private javax.swing.JLabel jlbPontos;
    private javax.swing.JLabel jlbReais;
    private javax.swing.JLabel jlbUfir;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfCompetencia;
    private javax.swing.JTextField jtfGravidade;
    private javax.swing.JTextField jtfNomeGravidade;
    private javax.swing.JTextField jtfPeso;
    private javax.swing.JTextField jtfPontos;
    private javax.swing.JTextField jtfUfir;
    private javax.swing.JTextPane jtpDescricao;
    private javax.swing.JTextPane jtpPenalidade;
    // End of variables declaration//GEN-END:variables

}
