/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Multa.java
 *
 * Created on 09/12/2009, 08:46:37
 */

package controle;

import classes.Combo;
import classes.ConexaoAccess;
import classes.Funcoes;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.NumberFormat;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeferson
 */
public class Multa extends javax.swing.JInternalFrame {

    private ConexaoAccess Conexao;
    private Funcoes Fun;

    /** Creates new form Multa */
    public Multa() {
        initComponents();
        JogarMotorista();
        JogarVeiculo();
        JogarMulta();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbMotorista = new javax.swing.JLabel();
        cboMotorista = new javax.swing.JComboBox();
        jlbVeiculo = new javax.swing.JLabel();
        cboVeiculo = new javax.swing.JComboBox();
        cboMulta = new javax.swing.JComboBox();
        jlbMulta = new javax.swing.JLabel();
        jlbCompetencia = new javax.swing.JLabel();
        jlbCompetencia1 = new javax.swing.JLabel();
        jlbGravidade = new javax.swing.JLabel();
        jlbGravidade1 = new javax.swing.JLabel();
        jlbValor = new javax.swing.JLabel();
        jlbValor1 = new javax.swing.JLabel();
        jlbCodigo = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jlbData = new javax.swing.JLabel();
        jtfData = new javax.swing.JFormattedTextField();
        jbtNovo = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();
        jbtExcluir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Lançamento de Multas");

        jlbMotorista.setText("Motorista");

        cboMotorista.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlbVeiculo.setText("Veículo");

        cboVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboMulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMultaActionPerformed(evt);
            }
        });

        jlbMulta.setText("Multa");

        jlbCompetencia.setText("Competência");

        jlbCompetencia1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbGravidade.setText("Gravidade");

        jlbGravidade1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbValor.setText("Valor");

        jlbValor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbCodigo.setText("Código");

        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyPressed(evt);
            }
        });

        jlbData.setText("Data");

        jtfData.setFormatterFactory(Fun.setFormatoData());

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtPesquisar))
                    .addComponent(cboMulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbData)
                                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlbMulta)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbCompetencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbCompetencia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbGravidade)
                                    .addComponent(jlbGravidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbValor)
                                    .addComponent(jlbValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 362, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbMotorista)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cboMotorista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbVeiculo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodigo)
                    .addComponent(jlbData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMotorista)
                    .addComponent(jlbVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCompetencia)
                    .addComponent(jlbValor)
                    .addComponent(jlbGravidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbValor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbGravidade1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbCompetencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtSalvar)
                        .addComponent(jbtNovo))
                    .addComponent(jbtExcluir)
                    .addComponent(jbtPesquisar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMultaActionPerformed
        if (cboMulta.getItemCount()>0){
            DadosInfracoes();
        }
    }//GEN-LAST:event_cboMultaActionPerformed

    private void jtfCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            String SQL;

            SQL = "select tlm.codigo, to_char(tlm.data,'DD/MM/YYYY') as datamulta, tlm.cpf_cod, (tmo.nome) as NomeMotorista, ";
            SQL = SQL + "tlm.chassis_cod, tve.placa, ";
            SQL = SQL + "tlm.multa_cod, tpm.descricao, tpm.competencia, tpm.pontuacao, tpm.ufir, tpm.peso ";
            SQL = SQL + "from t_lancamento_multa tlm ";
            SQL = SQL + "inner join t_motorista tmo on tmo.cpf = tlm.cpf_cod ";
            SQL = SQL + "inner join t_veiculo tve on tve.chassis = tlm.chassis_cod ";
            SQL = SQL + "inner join t_multa tpm on tpm.codigo = tlm.multa_cod ";
            SQL = SQL + "where tlm.codigo = " + jtfCodigo.getText() + " ";
            SQL = SQL + "and tlm.exclusao = 0 ";

            Conexao = new ConexaoAccess();
            Conexao.Conectar() ;
            Conexao.setSQL(SQL);

            ResultSet RS = Conexao.Consultar();

            try{
                if (RS.next()){

                    jtfCodigo.setText(RS.getString("codigo"));
                    jtfData.setText(RS.getString("datamulta"));

                    Combo Mot = new Combo(RS.getString("cpf_cod"), RS.getString("NomeMotorista"));
                    ComboBoxModel CBM;
                    CBM = cboVeiculo.getModel();
                    CBM.setSelectedItem(Mot);

                    Combo Vei = new Combo(RS.getString("chassis_cod"), RS.getString("placa"));
                    ComboBoxModel CBV;
                    CBV = cboVeiculo.getModel();
                    CBV.setSelectedItem(Vei);

                    Combo Mul = new Combo(RS.getString("multa_cod"), RS.getString("descricao"));
                    ComboBoxModel CB;
                    CB = cboMulta.getModel();
                    CB.setSelectedItem(Mul);

                    jlbGravidade1.setText(NivelMulta(Integer.parseInt(RS.getString("pontuacao"))));
                    jlbCompetencia1.setText("competencia");

                    int ufir = Integer.parseInt(RS.getString("ufir"));
                    int peso = Integer.parseInt(RS.getString("peso"));

                    jlbValor1.setText(NumberFormat.getCurrencyInstance().format(PrecoMulta(ufir, peso)));

                    jtfData.requestFocus();
                    
                }
            }catch (Exception Erro){
                JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
            }
        }
    }//GEN-LAST:event_jtfCodigoKeyPressed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed

        Limpar();

        cboMotorista.requestFocus();
        
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        Conexao = new ConexaoAccess();
        Conexao.Conectar();

        if (jtfCodigo.getText().equals("")){
            jtfCodigo.setText("0");
        }

        String sSQL = "select * from t_lancamento_multa where codigo = " + jtfCodigo.getText() + " ";
        Conexao.setSQL(sSQL);
        ResultSet RS = Conexao.Consultar();

        String Motorista = ((Combo)cboMotorista.getSelectedItem()).getKey();
        String Veiculo = ((Combo)cboVeiculo.getSelectedItem()).getKey();
        String Multa = ((Combo)cboMulta.getSelectedItem()).getKey();

        try {

            Fun = new Funcoes();
            String Data;

            if (!(Fun.isValidDate(jtfData.getText()))){
                Data = null;
            } else {
                Data = "'" + jtfData.getText() + "'";
            }

            if(RS.next()){
                String SQL;

                SQL = "update t_lancamento_multa set data = " + Data + ", cpf_cod = '" + Motorista + "', ";
                SQL = SQL + "chassis_cod = '" + Veiculo + "', multa_cod = '" + Multa + "' ";
                SQL = SQL + "where codigo = " + jtfCodigo.getText();

                Conexao.setSQL(SQL);
                Conexao.Executar();
            } else {
                String SQL;
                String Proximo;
                
                Fun = new Funcoes();
                Proximo = Fun.Proximo("t_lancamento_multa");

                SQL = "insert into t_lancamento_multa (codigo, data, cpf_cod, chassis_cod, multa_cod, exclusao) values (";
                SQL = SQL + Proximo + ", " + Data + ", '" + Motorista + "', '" + Veiculo + "', '";
                SQL = SQL + Multa + "', 0)";

                Conexao.setSQL(SQL);
                Conexao.Executar();
            }
        } catch (Exception Erro) {
            JOptionPane.showMessageDialog(null, "(Erro na validação): " + Erro);
        }

        Conexao.Desconectar();

        Limpar();

        jtfData.requestFocus();
        
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed

//        PesquisaRestricao A = new PesquisaRestricao();
//        A.setVisible(true);
//        JDesktopPane JDP = this.getDesktopPane();
//        JDP.add(A);
//        A.centralizar(JDP);
//        try{
//            A.setSelected(true);
//            A.SetRestricao(this);
//        }catch (Exception E){
//            JOptionPane.showMessageDialog(null, "Erro: " + E);
//        }
//        A.setVisible(true);
        
    }//GEN-LAST:event_jbtPesquisarActionPerformed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        Object[] botoes = { "Sim", "Não" };

        int resposta;

        resposta = JOptionPane.showOptionDialog(null, "Você deseja realmente excluir este registro?", "Confirma exclusão", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

        if(resposta == JOptionPane.YES_OPTION){
        
            String SQL = "update t_lancamento_multa set exclusao = 1 where codigo = " + jtfCodigo.getText() + "";

            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL(SQL);
            Conexao.Executar();
            Conexao.Desconectar();

            Limpar();

        }

        jtfData.requestFocus();
        
    }//GEN-LAST:event_jbtExcluirActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Multa().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    private void Limpar(){

        jtfCodigo.setText("");
        jtfData.setText("");

        cboMotorista.removeAllItems();
        JogarMotorista();

        cboVeiculo.removeAllItems();
        JogarVeiculo();

        cboMulta.removeAllItems();
        JogarMulta();

        jlbGravidade1.setText("");
        jlbCompetencia1.setText("");
        jlbValor1.setText("");

    }

    private void JogarMotorista(){
        cboMotorista.removeAllItems();
        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL("select (cpf) as codigo, nome from t_motorista where exclusao = 0 order by nome");
            ResultSet RS = Conexao.Consultar();
            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
            while(RS.next()){
                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
                Modelo.addElement(CB);
            }
            cboMotorista.setModel(Modelo);
        } catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }
    }

    private void JogarVeiculo(){
        cboVeiculo.removeAllItems();
        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL("select (chassis) as codigo, (placa) as nome from t_veiculo where exclusao = 0 order by nome");
            ResultSet RS = Conexao.Consultar();
            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
            while(RS.next()){
                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
                Modelo.addElement(CB);
            }
            cboVeiculo.setModel(Modelo);
        } catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }
    }

    private void JogarMulta(){
        cboMulta.removeAllItems();
        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL("select codigo, (descricao) as nome from t_multa where exclusao = 0 order by descricao");
            ResultSet RS = Conexao.Consultar();
            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
            while(RS.next()){
                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
                Modelo.addElement(CB);
            }
            cboMulta.setModel(Modelo);
        } catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }
    }

    private void DadosInfracoes(){

        String Multa = ((Combo)cboMulta.getSelectedItem()).getKey();

        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();

            String SQL;

            SQL = "select competencia, pontuacao, ufir, peso from t_multa where codigo = '";
            SQL = SQL + Multa + "' and exclusao = 0 ";

            Conexao.setSQL(SQL);
            ResultSet RS = Conexao.Consultar();

            if (RS.next()){
                jlbCompetencia1.setText(RS.getString("competencia"));

                Fun = new Funcoes();
                jlbGravidade1.setText(Fun.GravidadeMulta(Integer.parseInt(RS.getString("pontuacao"))));
                
                Fun = new Funcoes();

                int Ufir;
                int Peso;
                Double ValorUfir;

                Ufir = Integer.parseInt(RS.getString("ufir"));
                Peso = Integer.parseInt(RS.getString("peso"));
                ValorUfir = Fun.ValorUfir(Ufir, Peso);

                jlbValor1.setText(NumberFormat.getCurrencyInstance().format(ValorUfir));
            }
        }catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }

    }

    private String NivelMulta(int codigo){

        String NM=null;

        Fun = new Funcoes();
        NM = Fun.GravidadeMulta(codigo);

        return NM;

    }

    private double PrecoMulta(int ufir, int peso){

        double preco;

        Fun = new Funcoes();

        preco = Fun.ValorUfir(ufir, peso);

        return preco;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboMotorista;
    private javax.swing.JComboBox cboMulta;
    private javax.swing.JComboBox cboVeiculo;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JLabel jlbCompetencia;
    private javax.swing.JLabel jlbCompetencia1;
    private javax.swing.JLabel jlbData;
    private javax.swing.JLabel jlbGravidade;
    private javax.swing.JLabel jlbGravidade1;
    private javax.swing.JLabel jlbMotorista;
    private javax.swing.JLabel jlbMulta;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JLabel jlbValor1;
    private javax.swing.JLabel jlbVeiculo;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JFormattedTextField jtfData;
    // End of variables declaration//GEN-END:variables

}
