/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Sobre.java
 *
 * Created on 13/01/2010, 10:49:23
 */

package controle;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author Jeferson
 */
public class Sobre extends javax.swing.JInternalFrame {

   /** Creates new form Sobre */
    public Sobre() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbImagemJava = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbTH_Logo = new javax.swing.JLabel();
        jlbDescricao = new javax.swing.JLabel();
        jlbLogoWindows = new javax.swing.JLabel();
        jlbLinux = new javax.swing.JLabel();
        jlbFreebsd = new javax.swing.JLabel();
        jlbMacLogo = new javax.swing.JLabel();
        jlbPostgresqlLogo = new javax.swing.JLabel();
        jlbSistemas = new javax.swing.JLabel();
        jlbDesenvolvimento = new javax.swing.JLabel();
        jlbNetbeansLogo = new javax.swing.JLabel();
        jlbSolaris_Logo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Sobre o Sistema");

        jlbImagemJava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Java_Logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema de Frota 0.1 - Release Candidate 3");

        jlbTH_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TH_Logo.png"))); // NOI18N

        jlbDescricao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDescricao.setText("Programa para controle de frota de veículos");

        jlbLogoWindows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Windows_Logo.png"))); // NOI18N

        jlbLinux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linux_Logo.png"))); // NOI18N

        jlbFreebsd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/freebsd_logo.png"))); // NOI18N

        jlbMacLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Apple_Logo.png"))); // NOI18N

        jlbPostgresqlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Postgresql_logo.png"))); // NOI18N

        jlbSistemas.setText("Sistemas Suportados");

        jlbDesenvolvimento.setText("Desenvolvido em");

        jlbNetbeansLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/netbeans-logo.png"))); // NOI18N

        jlbSolaris_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/solaris.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbTH_Logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(jlbSistemas))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(105, 105, 105)
                                            .addComponent(jlbDesenvolvimento))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jlbNetbeansLogo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jlbImagemJava)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jlbPostgresqlLogo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbLogoWindows)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbLinux)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbFreebsd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbMacLogo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbSolaris_Logo)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbTH_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbSistemas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbLinux)
                    .addComponent(jlbLogoWindows)
                    .addComponent(jlbFreebsd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlbSolaris_Logo)
                        .addComponent(jlbMacLogo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbDesenvolvimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbPostgresqlLogo)
                        .addGap(10, 10, 10))
                    .addComponent(jlbImagemJava)
                    .addComponent(jlbNetbeansLogo))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbDescricao;
    private javax.swing.JLabel jlbDesenvolvimento;
    private javax.swing.JLabel jlbFreebsd;
    private javax.swing.JLabel jlbImagemJava;
    private javax.swing.JLabel jlbLinux;
    private javax.swing.JLabel jlbLogoWindows;
    private javax.swing.JLabel jlbMacLogo;
    private javax.swing.JLabel jlbNetbeansLogo;
    private javax.swing.JLabel jlbPostgresqlLogo;
    private javax.swing.JLabel jlbSistemas;
    private javax.swing.JLabel jlbSolaris_Logo;
    private javax.swing.JLabel jlbTH_Logo;
    // End of variables declaration//GEN-END:variables

}
