/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Veiculo.java
 *
 * Created on 30/10/2009, 07:50:40
 */

package controle;

import classes.Combo;
import classes.ConexaoAccess;
import classes.Funcoes;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeferson
 */
public class Veiculo extends javax.swing.JInternalFrame {

    private ConexaoAccess Conexao;
    private Funcoes Fun;

    /** Creates new form Veiculo */
    public Veiculo() {
        initComponents();
        JogarTipoVeiculo();
//        JogarNomeModelo();
        JogarNomeCor();
        JogarNomeCombustivel();
//        JogarNomeCarroceria();
//        JogarNomeEspecie();
        Modelo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbChassis = new javax.swing.JLabel();
        jtfChassis = new javax.swing.JTextField();
        jlbPlaca = new javax.swing.JLabel();
        jtfPlaca = new javax.swing.JTextField();
        jlbCor = new javax.swing.JLabel();
        jblTipoVeiculo = new javax.swing.JLabel();
        jlbRenavam = new javax.swing.JLabel();
        jtfRenavam = new javax.swing.JTextField();
        jtfNomeCidade = new javax.swing.JTextField();
        jtfCidade_Cod = new javax.swing.JTextField();
        jlbCidade = new javax.swing.JLabel();
        jlbCertificao = new javax.swing.JLabel();
        jtfCertificado = new javax.swing.JTextField();
        jlbQtdeEixos = new javax.swing.JLabel();
        jtfQtdeEixos = new javax.swing.JTextField();
        jlbModelo = new javax.swing.JLabel();
        jlbAno = new javax.swing.JLabel();
        jtfAno = new javax.swing.JTextField();
        jlbCapacidade = new javax.swing.JLabel();
        jtfCapacidade = new javax.swing.JTextField();
        cboTipo_Veiculo = new javax.swing.JComboBox();
        jtfEstado = new javax.swing.JTextField();
        jtfMarca = new javax.swing.JTextField();
        jlbCombustivel = new javax.swing.JLabel();
        cboCor = new javax.swing.JComboBox();
        cboCombustivel = new javax.swing.JComboBox();
        jlbCarroceria = new javax.swing.JLabel();
        jlbEspecie = new javax.swing.JLabel();
        jbtExcluir = new javax.swing.JButton();
        jbtPesquisar = new javax.swing.JButton();
        jbtSalvar = new javax.swing.JButton();
        jbtNovo = new javax.swing.JButton();
        jtfModelo_Cod = new javax.swing.JTextField();
        jtfNomeModelo = new javax.swing.JTextField();
        jlbMarca = new javax.swing.JLabel();
        jtfCarroceria_Cod = new javax.swing.JFormattedTextField();
        jtfNomeCarroceria = new javax.swing.JFormattedTextField();
        jtfEspecie_Cod = new javax.swing.JFormattedTextField();
        jtfNomeEspecie = new javax.swing.JFormattedTextField();
        jlbSemParar = new javax.swing.JLabel();
        jtfSemParar = new javax.swing.JFormattedTextField();
        jtfNumApolice = new javax.swing.JFormattedTextField();
        jlbNumApolice = new javax.swing.JLabel();
        jbtSeguro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jbtAtualizar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Cadastro de Veiculos");

        jlbChassis.setText("Chassis");

        jtfChassis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfChassisKeyPressed(evt);
            }
        });

        jlbPlaca.setText("Placa");

        jtfPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPlacaActionPerformed(evt);
            }
        });

        jlbCor.setText("Cor");

        jblTipoVeiculo.setText("Tipo Veículo");

        jlbRenavam.setText("Renavam");

        jtfRenavam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRenavamActionPerformed(evt);
            }
        });

        jtfNomeCidade.setEnabled(false);

        jtfCidade_Cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCidade_CodActionPerformed(evt);
            }
        });
        jtfCidade_Cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCidade_CodKeyPressed(evt);
            }
        });

        jlbCidade.setText("Cidade (F12)");

        jlbCertificao.setText("Certificado");

        jlbQtdeEixos.setText("QTDE Eixos");

        jlbModelo.setText("Modelo (F12)");

        jlbAno.setText("Ano");

        jlbCapacidade.setText("Capacidade");

        cboTipo_Veiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTipo_Veiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTipo_VeiculoItemStateChanged(evt);
            }
        });
        cboTipo_Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipo_VeiculoActionPerformed(evt);
            }
        });

        jtfEstado.setEnabled(false);

        jtfMarca.setEnabled(false);

        jlbCombustivel.setText("Combustível");

        cboCor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboCombustivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlbCarroceria.setText("Carroceria (F12)");

        jlbEspecie.setText("Espécie (F12)");

        jbtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        jbtExcluir.setText("Excluir");
        jbtExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirActionPerformed(evt);
            }
        });

        jbtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisa.png"))); // NOI18N
        jbtPesquisar.setText("Pesquisar");
        jbtPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPesquisarActionPerformed(evt);
            }
        });

        jbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        jbtSalvar.setText("Salvar");
        jbtSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalvarActionPerformed(evt);
            }
        });

        jbtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        jbtNovo.setText("Novo");
        jbtNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNovoActionPerformed(evt);
            }
        });

        jtfModelo_Cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfModelo_CodActionPerformed(evt);
            }
        });
        jtfModelo_Cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfModelo_CodKeyPressed(evt);
            }
        });

        jtfNomeModelo.setEnabled(false);

        jlbMarca.setText("Marca");

        jtfCarroceria_Cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCarroceria_CodKeyPressed(evt);
            }
        });

        jtfNomeCarroceria.setEditable(false);

        jtfEspecie_Cod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfEspecie_CodKeyPressed(evt);
            }
        });

        jtfNomeEspecie.setEditable(false);

        jlbSemParar.setText("Sem Parar");

        jtfNumApolice.setEnabled(false);

        jlbNumApolice.setText("Apólice Nº");

        jbtSeguro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartao.png"))); // NOI18N
        jbtSeguro.setText("Seguro");
        jbtSeguro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtSeguro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSeguroActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jbtAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Refresh2.png"))); // NOI18N
        jbtAtualizar.setText("Atualizar");
        jbtAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSeguro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtAtualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfModelo_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomeModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbModelo)
                                .addGap(203, 203, 203)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbMarca)
                            .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbAno)
                            .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCapacidade)
                            .addComponent(jtfCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboTipo_Veiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jblTipoVeiculo)
                                .addGap(108, 108, 108)
                                .addComponent(jlbCor)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNumApolice)
                            .addComponent(jtfNumApolice, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCarroceria)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCarroceria_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomeCarroceria)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbEspecie)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfEspecie_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNomeEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCertificao)
                                .addGap(184, 184, 184)
                                .addComponent(jlbQtdeEixos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfQtdeEixos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfCidade_Cod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomeCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbChassis)
                            .addComponent(jtfChassis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPlaca)
                            .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbRenavam)
                            .addComponent(jtfRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbCombustivel))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbSemParar)
                                .addGap(115, 115, 115))
                            .addComponent(jtfSemParar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbChassis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfChassis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbRenavam)
                            .addComponent(jlbSemParar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSemParar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblTipoVeiculo)
                            .addComponent(jlbCor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTipo_Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbCombustivel)
                            .addComponent(jlbNumApolice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumApolice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbCarroceria)
                            .addComponent(jlbEspecie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCarroceria_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNomeCarroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEspecie_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNomeEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfModelo_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNomeModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbAno)
                                    .addComponent(jlbMarca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCapacidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbCertificao)
                                    .addComponent(jlbQtdeEixos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfQtdeEixos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbCidade)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfCidade_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfNomeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtSalvar)
                                .addComponent(jbtNovo))
                            .addComponent(jbtExcluir)
                            .addComponent(jbtPesquisar)
                            .addComponent(jbtSeguro)))
                    .addComponent(jbtAtualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPlacaActionPerformed

    private void jtfRenavamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRenavamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRenavamActionPerformed

    private void jtfCidade_CodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCidade_CodActionPerformed

}//GEN-LAST:event_jtfCidade_CodActionPerformed

    private void jtfCidade_CodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCidade_CodKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            CarregaDados(jtfCidade_Cod.getText());
        }

        if(evt.getKeyCode() == KeyEvent.VK_F12){
            SubPesquisaCidade A = new SubPesquisaCidade();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
                A.SetSubPesquisaVeiculos(this);
                A.Validador("Veiculo");
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
        }

}//GEN-LAST:event_jtfCidade_CodKeyPressed

    private void JogarTipoVeiculo(){
        cboTipo_Veiculo.removeAllItems();
        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL("select codigo, nome from t_tipo_veiculo where exclusao = 0 order by nome");
            ResultSet RS = Conexao.Consultar();
            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
            while(RS.next()){
                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
                Modelo.addElement(CB);
            }
            cboTipo_Veiculo.setModel(Modelo);
        } catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }
    }

//    private void JogarNomeModelo(){
//        cboModelo.removeAllItems();
//        try {
//            Conexao = new ConexaoAccess();
//            Conexao.Conectar();
//            Conexao.setSQL("select codigo, nome from t_modelo where exclusao = 0 order by nome");
//            ResultSet RS = Conexao.Consultar();
//            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
//            while(RS.next()){
//                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
//                Modelo.addElement(CB);
//            }
//            cboModelo.setModel(Modelo);
//        } catch(Exception Erro){
//            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
//        }
//    }

    private void JogarNomeCor(){

        cboCor.removeAllItems();
        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL("select codigo, nome from t_tipo_cor where exclusao = 0 order by nome");
            ResultSet RS = Conexao.Consultar();
            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
            while(RS.next()){
                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
                Modelo.addElement(CB);
            }
            cboCor.setModel(Modelo);
        } catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }

    }

    private void JogarNomeCombustivel(){

        cboCombustivel.removeAllItems();
        try {
            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL("select codigo, nome from t_tipo_combustivel where exclusao = 0 order by nome");
            ResultSet RS = Conexao.Consultar();
            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
            while(RS.next()){
                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
                Modelo.addElement(CB);
            }
            cboCombustivel.setModel(Modelo);
        } catch(Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
        }

    }

//    private void JogarNomeCarroceria(){
//
//        cboCarroceria.removeAllItems();
//        try {
//            Conexao = new ConexaoAccess();
//            Conexao.Conectar();
//            Conexao.setSQL("select codigo, nome from t_tipo_carroceria where exclusao = 0 order by nome");
//            ResultSet RS = Conexao.Consultar();
//            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
//            while(RS.next()){
//                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
//                Modelo.addElement(CB);
//            }
//            cboCarroceria.setModel(Modelo);
//        } catch(Exception Erro){
//            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
//        }
//
//    }
//
//    private void JogarNomeEspecie(){
//
//        cboEspecie.removeAllItems();
//        try {
//            Conexao = new ConexaoAccess();
//            Conexao.Conectar();
//            Conexao.setSQL("select codigo, nome from t_tipo_especie where exclusao = 0 order by nome");
//            ResultSet RS = Conexao.Consultar();
//            DefaultComboBoxModel Modelo = new DefaultComboBoxModel();
//            while(RS.next()){
//                Combo CB = new Combo(RS.getString("codigo"),RS.getString("nome"));
//                Modelo.addElement(CB);
//            }
//            cboEspecie.setModel(Modelo);
//        } catch(Exception Erro){
//            JOptionPane.showMessageDialog(null, "Erro: " + Erro);
//        }
//
//    }

    private void cboTipo_VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipo_VeiculoActionPerformed
                
    }//GEN-LAST:event_cboTipo_VeiculoActionPerformed

    private void cboTipo_VeiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTipo_VeiculoItemStateChanged

    }//GEN-LAST:event_cboTipo_VeiculoItemStateChanged

    private void jtfChassisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfChassisKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            CarregaDados(jtfChassis.getText());
        }
        
    }//GEN-LAST:event_jtfChassisKeyPressed

    private void jbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirActionPerformed

        Object[] botoes = { "Sim", "Não" };
        
        int resposta;

        resposta = JOptionPane.showOptionDialog(null, "Você deseja realmente excluir este registro?", "Confirma exclusão", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);

        if(resposta == JOptionPane.YES_OPTION){

            String SQL = "update t_veiculo set exclusao = 1 where chassis = '" + jtfChassis.getText() + "'";

            Conexao = new ConexaoAccess();
            Conexao.Conectar();
            Conexao.setSQL(SQL);
            Conexao.Executar();
            Conexao.Desconectar();

            Limpar();

        }

        jtfChassis.requestFocus();
        
    }//GEN-LAST:event_jbtExcluirActionPerformed

    private void jbtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPesquisarActionPerformed

        PesquisaVeiculo A = new PesquisaVeiculo();
        A.setVisible(true);
        JDesktopPane JDP = this.getDesktopPane();
        JDP.add(A);
        A.centralizar(JDP);
        try{
            A.setSelected(true);
            A.SetVeiculo(this);
        }catch (Exception E){
            JOptionPane.showMessageDialog(null, "Erro: " + E);
        }
        A.setVisible(true);
        
    }//GEN-LAST:event_jbtPesquisarActionPerformed

    private void jbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalvarActionPerformed

        String TipoVeiculo = ((Combo)cboTipo_Veiculo.getSelectedItem()).getKey();
//        String codModelo = ((Combo)cboModelo.getSelectedItem()).getKey();
        String CodCor = ((Combo)cboCor.getSelectedItem()).getKey();
        String CodCombustivel = ((Combo)cboCombustivel.getSelectedItem()).getKey();
//        String CodCarroceria = ((Combo)cboCarroceria.getSelectedItem()).getKey();
//        String CodEspecie = ((Combo)cboEspecie.getSelectedItem()).getKey();

        Conexao = new ConexaoAccess();
        Conexao.Conectar();
        Conexao.setSQL("select * from t_veiculo where chassis = '" + jtfChassis.getText() + "' ");
        ResultSet RS = Conexao.Consultar();

        try {
            if(RS.next()){
                String SQL;
                SQL = "update t_veiculo set placa = '" + jtfPlaca.getText().toUpperCase() + "', tipo_cor = " + CodCor;
                SQL = SQL + ", tipo_veiculo = " + TipoVeiculo + ", renavam = '" + jtfRenavam.getText() + "', cidade_cod = ";
                SQL = SQL + jtfCidade_Cod.getText() + ", certificado = '" + jtfCertificado.getText() + "', qtde_eixo = ";
                SQL = SQL + jtfQtdeEixos.getText() + ", modelo_cod = " + jtfModelo_Cod.getText() + ", ano = " + jtfAno.getText();
                SQL = SQL + ", capacidade = '" + jtfCapacidade.getText() + "'";
                SQL = SQL + ", tipo_combustivel = " + CodCombustivel + ", tipo_especie = " + jtfEspecie_Cod.getText() + ", ";
                SQL = SQL + "tipo_carroceria = " + jtfCarroceria_Cod.getText() + ", semparar = '" + jtfSemParar.getText() + "' ";
                SQL = SQL + "where chassis = '" + jtfChassis.getText() + "'";
                Conexao.setSQL(SQL);
                Conexao.Executar();
            } else {
                String SQL;
                SQL = "insert into t_veiculo (chassis, placa, tipo_cor, tipo_veiculo, renavam, cidade_cod, certificado, qtde_eixo, ";
                SQL = SQL + "modelo_cod, ano, capacidade, tipo_combustivel, tipo_especie, tipo_carroceria, exclusao, semparar) values ('";
                SQL = SQL + jtfChassis.getText() + "', '" + jtfPlaca.getText().toUpperCase() + "', '";
                SQL = SQL + CodCor + "', " + TipoVeiculo + ", '" + jtfRenavam.getText() + "', ";
                SQL = SQL + jtfCidade_Cod.getText() + ", '" + jtfCertificado.getText() + "', " + jtfQtdeEixos.getText() + ", ";
                SQL = SQL + jtfModelo_Cod.getText() + ", " + jtfAno.getText() + ", '" + jtfCapacidade.getText() + "', " + CodCombustivel + ", ";
                SQL = SQL + jtfEspecie_Cod.getText() + ", " + jtfCarroceria_Cod.getText() + ", 0, '" + jtfSemParar.getText() + "')";
                Conexao.setSQL(SQL);
                Conexao.Executar();
            }

        } catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }

        Conexao.Desconectar();

        Limpar();

        jtfChassis.requestFocus();
        
    }//GEN-LAST:event_jbtSalvarActionPerformed

    private void jbtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNovoActionPerformed

        Limpar();

        jtfChassis.requestFocus();
        
    }//GEN-LAST:event_jbtNovoActionPerformed

    private void jtfModelo_CodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfModelo_CodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfModelo_CodActionPerformed

    private void jtfModelo_CodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfModelo_CodKeyPressed
     
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
//            CarregaDados(jtfModelo_Cod.getText());
            PuxaModelo(Integer.parseInt(jtfModelo_Cod.getText()));
        }

        if(evt.getKeyCode() == KeyEvent.VK_F12){
            SubPesquisaVeiculo A = new SubPesquisaVeiculo();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
                A.SetSubPequisaVeiculo(this);
                A.Validador("Veiculo");
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
        }
          
    }//GEN-LAST:event_jtfModelo_CodKeyPressed

    private void jtfCarroceria_CodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCarroceria_CodKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //CarregaDados(jtfCarroceria_Cod.getText());
            Carroceria();
        }

        if(evt.getKeyCode() == KeyEvent.VK_F12){
            SubPesquisaVeiculo A = new SubPesquisaVeiculo();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
                A.SetSubPequisaVeiculo(this);
                A.Validador("Carroceria");
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
        }
          
        
    }//GEN-LAST:event_jtfCarroceria_CodKeyPressed

    private void jtfEspecie_CodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEspecie_CodKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            Especie();
        }

        if(evt.getKeyCode() == KeyEvent.VK_F12){
            SubPesquisaVeiculo A = new SubPesquisaVeiculo();
            A.setVisible(true);
            JDesktopPane JDP = this.getDesktopPane();
            JDP.add(A);
            A.centralizar(JDP);
            try{
                A.setSelected(true);
                A.SetSubPequisaVeiculo(this);
                A.Validador("Espécie");
            }catch (Exception E){
                JOptionPane.showMessageDialog(null, "Erro: " + E);
            }
            A.setVisible(true);
        }
        
    }//GEN-LAST:event_jtfEspecie_CodKeyPressed

    private void jbtSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSeguroActionPerformed
        
        Seguro A = new Seguro();
        A.setVisible(true);
        JDesktopPane JDP = this.getDesktopPane();
        JDP.add(A);
        A.centralizar(JDP);
        try{
            A.setSelected(true);
            A.FuncaoGenerica("Veículo", jtfChassis.getText());
        }catch (Exception E){
            JOptionPane.showMessageDialog(null, "Erro: " + E);
        }
        A.setVisible(true);
        
    }//GEN-LAST:event_jbtSeguroActionPerformed

    private void jbtAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAtualizarActionPerformed
        
        if (!(jtfChassis.getText().equals(""))){
            jtfNumApolice.setText(NumeroSeguro(jtfChassis.getText()));
        }
                
    }//GEN-LAST:event_jbtAtualizarActionPerformed

    private void Modelo(){

        if (!(jtfModelo_Cod.getText().equals(""))){

            String codModelo = jtfModelo_Cod.getText();

            Fun = new Funcoes();
            jtfMarca.setText(Fun.Marca(Integer.parseInt(codModelo)));

        }

    }

    private void Carroceria(){

        if (!(jtfCarroceria_Cod.getText().equals(""))){

            String codCarroceria = jtfCarroceria_Cod.getText();

            Fun = new Funcoes();
            jtfNomeCarroceria.setText(Fun.Carroceria(Integer.parseInt(codCarroceria)));

        }

    }
    
    private void Especie(){

        if (!(jtfEspecie_Cod.getText().equals(""))){

            String codEspecie = jtfEspecie_Cod.getText();

            Fun = new Funcoes();
            jtfNomeEspecie.setText(Fun.Especie(Integer.parseInt(codEspecie)));

        }

    }
    
    public void PuxaModelo(int Codigo){
        
        String SQL;
        
        SQL = "select tmo.codigo, tmo.nome, (tma.nome) as marca ";
        SQL = SQL + "from t_modelo tmo ";
        SQL = SQL + "inner join t_marca tma on tma.codigo = tmo.marca_cod ";
        SQL = SQL + "where tmo.codigo = " + Codigo + " ";
        SQL = SQL + "and tmo.exclusao = 0 ";

        Conexao = new ConexaoAccess();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ResultSet RS = Conexao.Consultar();

        try{
            if (RS.next()){

                jtfModelo_Cod.setText(RS.getString("codigo"));
                jtfNomeModelo.setText(RS.getString("nome"));
                jtfMarca.setText(RS.getString("marca"));
                
            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }
        
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veiculo().setVisible(true);
            }
        });
    }

    public void centralizar(JDesktopPane dp) {
        Dimension ds = dp.getSize();
        Dimension dw = this.getSize();
        this.setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    public void CarregaDados(String Codigo){

        String SQL;
        
        SQL = "select tve.chassis, tve.placa, tve.tipo_cor, (ttc.nome) as cor, tve.tipo_veiculo, (ttv.nome) as nome_veiculo, tve.renavam, ";
        SQL = SQL + "tve.cidade_cod, tcd.cidade, tve.certificado, tve.qtde_eixo, modelo_cod, (tmd.nome) as modelo, ";
        SQL = SQL + "tve.ano, tve.capacidade, (tma.nome) as marca, ";
        SQL = SQL + "tipo_combustivel, (ttcb.nome) as combustivel, tipo_especie, (tte.nome) as especie, ";
	SQL = SQL + "tipo_carroceria, (ttca.nome) as carroceria, tve.semparar ";
        SQL = SQL + "from t_veiculo tve ";
        SQL = SQL + "inner join t_tipo_veiculo ttv on ttv.codigo = tve.tipo_veiculo ";
        SQL = SQL + "inner join t_modelo tmd on tmd.codigo = tve.modelo_cod ";
        SQL = SQL + "inner join t_marca tma on tma.codigo = tmd.marca_cod ";
        SQL = SQL + "inner join cidade tcd on tcd.codcidade = tve.cidade_cod ";        
        SQL = SQL + "inner join t_tipo_cor ttc on ttc.codigo = tve.tipo_cor ";
        SQL = SQL + "inner join t_tipo_combustivel ttcb on ttcb.codigo = tve.tipo_combustivel ";
        SQL = SQL + "inner join t_tipo_especie tte on tte.codigo = tve.tipo_especie ";
        SQL = SQL + "inner join t_tipo_carroceria ttca on ttca.codigo = tve.tipo_carroceria ";
        SQL = SQL + "where tve.chassis = '" + Codigo + "' ";
        SQL = SQL + "and tve.exclusao = 0 ";

        Conexao = new ConexaoAccess();
        Conexao.Conectar() ;
        Conexao.setSQL(SQL);

        ResultSet RS = Conexao.Consultar();

        try{
            if (RS.next()){
                jtfChassis.setText(RS.getString("chassis"));
                jtfPlaca.setText(RS.getString("placa"));
                
                Combo Tipo_VE = new Combo(RS.getString("tipo_veiculo"), RS.getString("nome_veiculo"));
                ComboBoxModel CMB;
                CMB = cboTipo_Veiculo.getModel();
                CMB.setSelectedItem(Tipo_VE);

                jtfRenavam.setText(RS.getString("Renavam"));
                jtfCidade_Cod.setText(RS.getString("cidade_cod"));

                Fun = new Funcoes();
                jtfNomeCidade.setText(Fun.NomeCidade(Integer.parseInt(jtfCidade_Cod.getText())));
                jtfEstado.setText(Fun.SiglaEstado(Integer.parseInt(jtfCidade_Cod.getText())));

                jtfCertificado.setText(RS.getString("Certificado"));
                jtfQtdeEixos.setText(RS.getString("qtde_eixo"));

//                Combo Mo = new Combo(RS.getString("modelo_cod"), RS.getString("modelo"));
//                ComboBoxModel CBM;
//                CBM = cboModelo.getModel();
//                CBM.setSelectedItem(Mo);
                
                jtfModelo_Cod.setText(RS.getString("modelo_cod"));
                jtfNomeModelo.setText(RS.getString("modelo"));
                jtfMarca.setText(RS.getString("marca"));

                jtfAno.setText(RS.getString("ano"));
                jtfCapacidade.setText(RS.getString("capacidade"));

                Combo Cor = new Combo(RS.getString("tipo_cor"), RS.getString("cor"));
                ComboBoxModel ComboCor;
                ComboCor = cboCor.getModel();
                ComboCor.setSelectedItem(Cor);

                Combo Combustivel = new Combo(RS.getString("tipo_combustivel"), RS.getString("combustivel"));
                ComboBoxModel ComboCombustivel;
                ComboCombustivel = cboCombustivel.getModel();
                ComboCombustivel.setSelectedItem(Combustivel);
                
//                Combo Especie = new Combo(RS.getString("tipo_especie"), RS.getString("especie"));
//                ComboBoxModel ComboEspecie;
//                ComboEspecie = cboEspecie.getModel();
//                ComboEspecie.setSelectedItem(Especie);
//
//                Combo Carroceria = new Combo(RS.getString("tipo_carroceria"), RS.getString("carroceria"));
//                ComboBoxModel ComboCarroceria;
//                ComboCarroceria = cboCarroceria.getModel();
//                ComboCarroceria.setSelectedItem(Carroceria);
                
                jtfNumApolice.setText(NumeroSeguro(RS.getString("chassis")));
                
                jtfEspecie_Cod.setText(RS.getString("tipo_especie"));
                jtfNomeEspecie.setText(RS.getString("especie"));
                jtfCarroceria_Cod.setText(RS.getString("tipo_carroceria"));
                jtfNomeCarroceria.setText(RS.getString("carroceria"));
                jtfSemParar.setText(RS.getString("semparar"));
                
            }
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação: " + Erro);
        }
        jtfPlaca.requestFocus();
        Conexao.Desconectar();

    }

    public void BuscaCidade(int Codigo){

        Fun = new Funcoes();
        jtfCidade_Cod.setText(String.valueOf(Codigo));
        jtfNomeCidade.setText(Fun.NomeCidade(Codigo));
        jtfEstado.setText(Fun.SiglaEstado(Codigo));

    }

    private void Limpar(){

        jtfChassis.setText("");
        jtfPlaca.setText("");
        cboCor.removeAllItems();

        cboTipo_Veiculo.removeAllItems();
        JogarTipoVeiculo();

        jtfRenavam.setText("");
        jtfCidade_Cod.setText("");
        jtfNomeCidade.setText("");
        jtfEstado.setText("");
        jtfCertificado.setText("");
        jtfQtdeEixos.setText("");
        jtfModelo_Cod.setText("");        
        jtfNomeModelo.setText("");
        
//        cboModelo.removeAllItems();
//        JogarNomeModelo();
        
        jtfMarca.setText("");
        jtfAno.setText("");
        jtfCapacidade.setText("");

        cboCor.removeAllItems();
        JogarNomeCor();

        cboCombustivel.removeAllItems();
        JogarNomeCombustivel();

//        cboEspecie.removeAllItems();
//        JogarNomeEspecie();
//
//        cboCarroceria.removeAllItems();
//        JogarNomeCarroceria();

        jtfNumApolice.setText("");
        
        jtfEspecie_Cod.setText("");
        jtfNomeEspecie.setText("");        
        jtfCarroceria_Cod.setText("");
        jtfNomeCarroceria.setText("");
        jtfSemParar.setText("");
                
    }
    
    public String NumeroSeguro (String Chassis){
        
        String SQL=null;
        String Numero=null;
        
        try{
        
            SQL = "select (num_apolice) as nome from t_seguro where veiculo_cod = '" + Chassis + "' ";
            
            Fun = new Funcoes();
            Numero = Fun.FuncaoGenerica(SQL);
            
        }catch (Exception Erro){
            JOptionPane.showMessageDialog(null, "Erro na validação da função genérica: " + Erro);
        }
        
        return Numero;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCombustivel;
    private javax.swing.JComboBox cboCor;
    private javax.swing.JComboBox cboTipo_Veiculo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jblTipoVeiculo;
    private javax.swing.JButton jbtAtualizar;
    private javax.swing.JButton jbtExcluir;
    private javax.swing.JButton jbtNovo;
    private javax.swing.JButton jbtPesquisar;
    private javax.swing.JButton jbtSalvar;
    private javax.swing.JButton jbtSeguro;
    private javax.swing.JLabel jlbAno;
    private javax.swing.JLabel jlbCapacidade;
    private javax.swing.JLabel jlbCarroceria;
    private javax.swing.JLabel jlbCertificao;
    private javax.swing.JLabel jlbChassis;
    private javax.swing.JLabel jlbCidade;
    private javax.swing.JLabel jlbCombustivel;
    private javax.swing.JLabel jlbCor;
    private javax.swing.JLabel jlbEspecie;
    private javax.swing.JLabel jlbMarca;
    private javax.swing.JLabel jlbModelo;
    private javax.swing.JLabel jlbNumApolice;
    private javax.swing.JLabel jlbPlaca;
    private javax.swing.JLabel jlbQtdeEixos;
    private javax.swing.JLabel jlbRenavam;
    private javax.swing.JLabel jlbSemParar;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfCapacidade;
    private javax.swing.JFormattedTextField jtfCarroceria_Cod;
    private javax.swing.JTextField jtfCertificado;
    private javax.swing.JTextField jtfChassis;
    private javax.swing.JTextField jtfCidade_Cod;
    private javax.swing.JFormattedTextField jtfEspecie_Cod;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfModelo_Cod;
    private javax.swing.JFormattedTextField jtfNomeCarroceria;
    private javax.swing.JTextField jtfNomeCidade;
    private javax.swing.JFormattedTextField jtfNomeEspecie;
    private javax.swing.JTextField jtfNomeModelo;
    private javax.swing.JFormattedTextField jtfNumApolice;
    private javax.swing.JTextField jtfPlaca;
    private javax.swing.JTextField jtfQtdeEixos;
    private javax.swing.JTextField jtfRenavam;
    private javax.swing.JFormattedTextField jtfSemParar;
    // End of variables declaration//GEN-END:variables

}
